.github/dependabot.yml
.prettierrc.js

prettier to not add bracket spacing, dependabot ignore defichain

---

.github/governance.yml
.github/labels.yml

/kind chore
For better labelling of issues and pull requests.

added new issue/pr labels

---

.github/workflows/ci-size-limit.yml
.github/workflows/ci.yml
packages/jellyfish-core/__tests__/core.test.ts
packages/jellyfish-core/src/core.ts
packages/jellyfish-jsonrpc/__tests__/jsonrpc.test.ts
packages/jellyfish-jsonrpc/src/jsonrpc.ts
packages/jellyfish/src/jellyfish.ts
packages/testcontainers/__tests__/testcontainers.test.ts
packages/testcontainers/package.json
packages/testcontainers/src/testcontainers.ts

/kind chore
Code coverage provides at merge information to show reviewer where and how the code is tested. This allow reviewer to make critical decision when approving or rejecting a PR.

added codecov for coverage

---

README.md

/kind chore
Allow maintainer and library user to make informed decision when using and maintaining `@defichain/jellyfish` libraries.

added dependencies matrix

---

.github/workflows/ci-size-limit.yml
.github/workflows/ci.yml
package-lock.json
package.json

/kind chore
Added a more performant preset for size-limit so that it will work well across all browser.

tweaked size-limit with better kpi

---

README.md

/kind chore
Honestly, who loves tech debt. We need to massacre tech debt!

added codeclimate maintainability to detect tech debt

---

.github/PULL_REQUEST_TEMPLATE.md
package-lock.json
package.json

Bump size-limit from 4.9.2 to 4.10.1

---

.idea/dictionaries/fuxing.xml
.idea/vcs.xml
LICENSE
README.md
package.json
packages/jellyfish-core/package.json
packages/jellyfish-jsonrpc/package.json
packages/jellyfish/package.json
packages/testcontainers/package.json

/kind chore
1. Updated LICENSE to be 'Copyright (c) DeFiChain Jellyfish **Contributors**' instead of **Developers**
2. Updated README to include:
1. packages
2. build badge
3. short installation guide
4. short usage guide
The rest of the README are still WIP

update readme and license

---

netlify.toml
website/package-lock.json
website/package.json

/kind docs
- Continuously deploy docs website that are merged into main
- Continuously integrate docs website with preview at each pull request
- Make docs website deployment a no-op process for jellyfish development
- Bring visibility to documentation website at each pull request
Fixes #63

netlify config for automated web ci/cd

---

.idea/dictionaries/fuxing.xml
.idea/jellyfish.iml
package-lock.json
packages/network/README.md
packages/network/__tests__/index.test.ts
packages/network/jest.config.js
packages/network/package.json
packages/network/src/index.ts
packages/network/tsconfig.json

/kind feature
A new module: `network` for various network related config for the defichain project.
This is a requirement for #25 but is modularised.
Following the design of: https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/networks.js
Based on https://github.com/DeFiCh/ain/blob/master/src/chainparams.cpp

new network package for various network related config

---

packages/jellyfish-api-core/__tests__/category/blockchain.test.ts
packages/jellyfish-api-core/__tests__/category/mining.test.ts
packages/jellyfish-api-core/src/category/blockchain.ts
packages/jellyfish-api-core/src/category/mining.ts
packages/jellyfish-api-core/src/index.ts
website/docs/jellyfish/api/blockchain.md
website/sidebars.js

/kind feature
Implemented type for RPC: #48
1. blockchain.getBlockchainInfo

blockchain.getBlockchainInfo

---

.github/governance.yml
.github/labels.yml

/kind chore
As new projects get introduced the current area labels are outdated.

updated area label to include latest projects

---

packages/jellyfish-json/__tests__/remap.test.ts
packages/jellyfish-json/src/index.ts
packages/jellyfish-json/src/remap.ts

/kind fix
To cater any kinds of object structure on view
Fixes #
Add array handling on remap

remap array handling

---

.github/governance.yml
.github/labeler.yml
.github/labels.yml
.github/workflows/files-labeler.yml

/kind chore
As the mono repo is growing in size, added labeler to automatically label area of concern in each PR.

added labeler to automatically label area of concern in each PR

---

.idea/dictionaries/fuxing.xml
packages/jellyfish-api-core/__tests__/category/rawtx.test.ts
packages/jellyfish-api-core/src/category/rawtx.ts
packages/jellyfish-api-core/src/index.ts
website/docs/jellyfish/api/rawtx.md
website/sidebars.js

/kind feature
Added types for `rawtx.ts` #48 
1. createRawTransaction
2. signRawTransactionWithKey
3. testMempoolAccept
4. sendRawTransaction
I added `//TODO` comments for some parts of the code as it's beyond my scope to implement them. Need to work on others features now.

rawtx.createRawTransaction, rawtx.signRawTransactionWithKey, rawtx.testMempoolAccept, rawtx.sendRawTransaction

---

.github/CODEOWNERS
.github/governance.yml
.github/labeler.yml
.github/labels.yml
.github/workflows/oss-governance-labeler.yml

/kind chore
1. Updated CODEOWNERS to reflect current ownership.
2. Project renames and introduction of new project

updated governance, labels & codeowners

---

.idea/dictionaries/fuxing.xml
package-lock.json
package.json
packages/jellyfish-api-core/__tests__/category/mining.test.ts
packages/jellyfish-transaction/__tests__/index.test.ts
packages/jellyfish-transaction/__tests__/tx_signature/sign_transaction.test.ts
packages/jellyfish-transaction/src/index.ts
packages/jellyfish-transaction/src/tx_signature.ts

/kind refactor
deps changes and small refactor to mining.test.ts to make it less flaky

flaky test refactor and deps upgrade

---

packages/jellyfish-transaction/__tests__/script/defi/dftx_pool/PoolRemoveLiquidity.test.ts
packages/jellyfish-transaction/src/script/defi/dftx.ts
packages/jellyfish-transaction/src/script/defi/dftx_pool.ts
packages/jellyfish-transaction/src/script/mapping.ts

/kind feature
Added DfTx PoolRemoveLiquidity Buffer composing

added DfTx PoolRemoveLiquidity

---

packages/jellyfish-wallet-mnemonic/__tests__/mnemonic/bip32.test.ts

/kind fix
fixed flaky random bip32 test

fix flaky random bip32 test

---

packages/jellyfish-api-core/__tests__/category/blockchain.test.ts
packages/jellyfish-api-core/src/category/blockchain.ts
website/docs/jellyfish/api/blockchain.md

/kind feature
Add new getBlockHeader rpc

Add new getBlockHeader rpc

---

packages/jellyfish-transaction/src/script/defi/dftx_pool.ts

/kind fix
fixed CPoolSwap not to use bigint to parse due to platform issues

fixed CPoolSwap not to use bigint to parse

---

packages/jellyfish-transaction/__tests__/script/defi/dftx_token/TokenMint.test.ts
packages/jellyfish-transaction/src/script/defi/dftx.ts
packages/jellyfish-transaction/src/script/defi/dftx_token.ts
packages/jellyfish-transaction/src/script/mapping.ts

added DfTx TokenMint

---

packages/jellyfish-api-core/__tests__/category/net.test.ts
packages/jellyfish-api-core/src/category/net.ts
packages/jellyfish-api-core/src/index.ts
website/docs/jellyfish/api/net.md
website/sidebars.js

/kind feature
Add new getConnectionCount rpc

Add getConnectionCount rpc

---

packages/testcontainers/src/chains/container.ts

/kind fix
For testing container image that are not in dockerhub, this fix will only try to pull image if an image does not exist locally.

image will only try to pull if it did not already exist

---

packages/jellyfish-api-core/__tests__/category/net.test.ts
packages/jellyfish-api-core/src/category/net.ts
website/docs/jellyfish/api/net.md

/kind feature
Add new getNetworkInfo rpc

Add getNetworkInfo rpc

---

packages/jellyfish-transaction/__tests__/script/defi/dftx_token/TokenMint.test.ts
packages/jellyfish-transaction/src/script/defi/dftx_token.ts

fix dftx TokenMint

---

.github/CODEOWNERS

/kind chore
Due to recent contributions to api-core, @jingyi2811 has the context required to review api-core code.

added jingyi2811 to api-core codeowner

---

packages/jellyfish-api-core/__tests__/category/blockchain.test.ts
packages/jellyfish-api-core/src/category/blockchain.ts
website/docs/jellyfish/api/blockchain.md

/kind fix
1. Fixed `Vout.value` to be parsed as BigNumber
2. Moved `tokenId` from `Vout.scriptPubKey.tokenId` to `Vout.tokenId`

fix blockchain.ts BigNumber encoding and tokenId

---

packages/jellyfish-transaction/__tests__/script/index.test.ts
packages/jellyfish-transaction/__tests__/script/mapping.test.ts
packages/jellyfish-transaction/src/script/constants.ts
packages/jellyfish-transaction/src/script/mapping.ts

/kind feature
Add OP_1NEGATE opcode

Add OP_1NEGATE

---

packages/jellyfish-transaction/__tests__/script/index.test.ts
packages/jellyfish-transaction/__tests__/script/mapping.test.ts
packages/jellyfish-transaction/src/script/crypto.ts
packages/jellyfish-transaction/src/script/mapping.ts

/kind feature
Add crypto opcodes

Add crypto opcodes

---

.idea/dictionaries/fuxing.xml
packages/testcontainers/__tests__/chains/reg_test_container/masternode.test.ts
packages/testcontainers/src/chains/defid_container.ts
packages/testcontainers/src/chains/docker_container.ts
packages/testcontainers/src/chains/main_net_container.ts
packages/testcontainers/src/chains/reg_test_container/index.ts
packages/testcontainers/src/chains/reg_test_container/masternode.ts
packages/testcontainers/src/chains/reg_test_container/persistent.ts
packages/testcontainers/src/chains/test_net_container.ts
packages/testcontainers/src/index.ts

/kind refactor
Refactored testcontainers, adding more documents and container.waitForBlock utility method.

refactor testcontainers

---

packages/testcontainers/src/chains/defid_container.ts

Update testcontainers to 1.6.4, this fixes the infamous `txn-mempool-conflict` issue.

updated testcontainers to 1.6.4

---

packages/testing/README.md
packages/testing/__tests__/account.test.ts
packages/testing/src/account.ts
packages/testing/src/poolpair.ts
packages/testing/src/token.ts
packages/testing/src/wallet.ts

/kind feature
Added `sendtokenstoaddress` for `@defichain/testing`.
Fixes #222
- Fixed some JSDocs errors
- Also clean up test/code formatting
- Updated README for `@defichain/testing`

added sendTokensToAddress for /testing

---

packages/jellyfish-api-core/src/category/account.ts
website/docs/jellyfish/api/account.md

fixed AccountPagination.start interface only allow number

---

packages/jellyfish-api-core/__tests__/category/account.test.ts
packages/jellyfish-api-core/__tests__/category/poolpair.test.ts
packages/jellyfish-api-core/__tests__/category/token.test.ts
packages/jellyfish-api-core/src/category/account.ts
packages/testcontainers/README.md
packages/testcontainers/src/chains/reg_test_container/masternode.ts
packages/testing/__tests__/account.test.ts

/kind fix
optimize and fix known block gen flaky race conditions:
1. block gen race conditions are e.g. when mempool is flushed when block get generated
2. fixed mempool/list account history test correctness
3. remove `container.generate()` that don't require it to speed up tests
4. use `container.waitForWalletBalanceGTE()` that is faster than just using `container.generate()`
5. optimized `container.waitForWalletBalanceGTE()` to auto mint to get to target balance faster

optimize and fix known block gen flaky race conditions

---

.idea/dictionaries/fuxing.xml
packages/testing/__tests__/poolpair.test.ts
packages/testing/src/account.ts
packages/testing/src/poolpair.ts
packages/testing/src/token.ts

/kind feature
Added ability add/remove PoolLiquidity in `@defichain/testing`.
- Fixed docs and test correctness in `poolpair` as well.

`@defichain/testing` new add/remove PoolLiquidity for testing

---

package-lock.json
packages/jellyfish-wallet/__tests__/account.mock.ts
packages/jellyfish-wallet/__tests__/wallet.test.ts
packages/jellyfish-wallet/__tests__/wallet_account.test.ts
packages/jellyfish-wallet/package.json
packages/jellyfish-wallet/src/wallet_account.ts

/kind feature
`jellyfish-wallet` needs to be updated to support the evolving `jellyfish-*` design changes
Fixes #140

`jellyfish-wallet` updated for `txn-builder` compatibility

---

.github/CODEOWNERS
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_p2wpkh.test.ts
packages/jellyfish-transaction-builder/src/txn/txn_builder.ts

/kind fix
total vin, total vout not tally for built transaction
Fixes #

fix custom tx vout not deducted

---

packages/jellyfish-transaction/__tests__/buffer/buffer_composer.test.ts
packages/jellyfish-transaction/src/buffer/buffer_composer.ts
packages/jellyfish-transaction/src/tx_composer.ts
packages/jellyfish-transaction/src/tx_segwit.ts

/kind feature
1. rename `BufferComposer.hex` to `BufferComposer.hexLE`
2. added `BufferComposer.hexBE`
3. added `BufferComposer.utf8LE`
4. added `BufferComposer.utf8BE`
Also implemented in https://github.com/DeFiCh/jellyfish/pull/233 but moved into this PR so that https://github.com/DeFiCh/jellyfish/pull/247 can use it

added hexBE, utf8LE, utf8BE, refactor hexLE

---

packages/jellyfish-address/__tests__/base58_address.test.ts
packages/jellyfish-address/__tests__/bech32_address.test.ts
packages/jellyfish-address/__tests__/p2pkh.test.ts
packages/jellyfish-address/__tests__/p2sh.test.ts
packages/jellyfish-address/__tests__/p2wpkh.test.ts
packages/jellyfish-address/__tests__/p2wsh.test.ts
packages/jellyfish-address/src/index.ts
packages/jellyfish-address/src/p2pkh.ts
packages/jellyfish-address/src/p2sh.ts
packages/jellyfish-address/src/p2wpkh.ts
packages/jellyfish-address/src/p2wsh.ts

/kind fix
`@defichain/jellyfish-transaction/src/*` is wrong it should be `@defichain/jellyfish-transaction`

fix import error using wrong import directory

---

packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_p2wpkh.test.ts
packages/jellyfish-transaction/__tests__/buffer/buffer_composer.test.ts
packages/jellyfish-transaction/src/buffer/buffer_composer.ts

/kind feature
- Added `varUIntUtf8LE` and `varUIntUtf8BE`.
- Also added a note to refactor hexLE, hexBE

added varUIntUtf8 LE/BE

---

packages/testing/__tests__/account.test.ts
packages/testing/src/account.ts

/kind fix
Should `container.generate(1)` after sending tokens as testing module be fully featured. This removes the need to `container.generate(1)` from setup code..

fix send tokens to address should generate

---

.github/workflows/ci.yml

/kind chore
CI script not failing as it attempts to fix.

fixed ci script not failing

---

.github/workflows/oss-governance-project.yml

/kind chore
All non-forked pull request in this repo should be added to project board, this automates the process.

oss-governance-project to auto update project board

---

.github/workflows/oss-governance-project.yml

oss-governance-project update due to board changes

---

.github/CODEOWNERS
.idea/dictionaries/fuxing.xml

/kind chore
Updated code ownership due to recent contributions and ongoing contributions.

updated CODEOWNERS

---

.github/workflows/oss-governance-project.yml

fix oss-governance-project not to trigger for bot

---

package-lock.json
packages/jellyfish-transaction-builder/__tests__/test.utils.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_account_utxos_to_account.test.ts
packages/jellyfish-transaction-builder/src/index.ts
packages/jellyfish-transaction-builder/src/txn/txn_builder_account.ts
packages/jellyfish-transaction-builder/src/txn/txn_builder_error.ts

/kind feature
FE dev friendly DfTx builder (utxos to account)
Fixes part of #244

`txn-builder`: utxos-to-account

---

.github/CODEOWNERS

updated CODEOWNERS due to recent ownership activity

---

packages/jellyfish-api-core/src/category/wallet.ts

fix: changed avoid_reuse to false

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/oss-governance-bot.yml
.github/workflows/oss-governance-labeler.yml
.github/workflows/oss-governance-project.yml
.github/workflows/release-publish.yml
.github/workflows/sync-labels.yml

/kind chore
- Fixed all workflow actions version to a commit SHA.
- Added self-assign workflow

updated & cleanup `.github/workflows`

---

packages/jellyfish-transaction/__tests__/script/defi/dftx_misc/AutoAuthPrep.test.ts
packages/jellyfish-transaction/src/script/defi/dftx.ts
packages/jellyfish-transaction/src/script/defi/dftx_misc.ts
packages/jellyfish-transaction/src/script/mapping.ts

/kind feature
Parse auto-auto transaction, mainly for explorer
Fixes #

`dftx-scripting`: auto-auth-prep

---

packages/jellyfish-api-core/__tests__/category/blockchain.test.ts
packages/jellyfish-api-core/src/category/blockchain.ts
website/docs/jellyfish/api/blockchain.md

Add getDifficulty
/kind feature
Add getDifficulty rpc

Add `blockchain.getDifficulty` RPC

---

packages/jellyfish-api-core/__tests__/category/mining.test.ts
packages/jellyfish-api-core/__tests__/category/token.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_account_account_to_account.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_dex_poolswap.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_liq_pool_add_liquidity.test.ts
packages/testcontainers/__tests__/index.test.ts
packages/testcontainers/src/chains/defid_container.ts
packages/testcontainers/src/chains/reg_test_container/index.ts
packages/testing/__tests__/account.test.ts
packages/testing/__tests__/poolpair.test.ts

/kind chore
This is a regression test against 1.7.x branch of ain, a PR is created in order to run tests on CICD.

Update `@defichain/testcontainers` to 1.7.0

---

.github/workflows/oss-governance-project-issue.yml

/kind fix
Error with action not formatted properly.

fix project governance to auto move card based on priority label

---

packages/jellyfish-transaction/__tests__/buffer/buffer_composer.test.ts
packages/jellyfish-transaction/__tests__/script/defi/dftx_masternode/CreateMasterNode.test.ts
packages/jellyfish-transaction/__tests__/script/defi/dftx_masternode/ResignMasterNode.test.ts
packages/jellyfish-transaction/src/buffer/buffer_composer.ts
packages/jellyfish-transaction/src/script/defi/dftx.ts
packages/jellyfish-transaction/src/script/defi/dftx_masternode.ts
packages/jellyfish-transaction/src/script/mapping.ts

/kind feature
- for explorer to decode
- to create/resign masternode in future
Fixes #

Add `DfTx` for Create & Resign MasterNode

---

packages/jellyfish-api-core/__tests__/category/blockchain.test.ts
packages/jellyfish-api-core/src/category/blockchain.ts
website/docs/jellyfish/api/blockchain.md

/kind Feature
implementation of RCP #48 
Fixes #

Add `blockchain.getBlockStats`, `blockchain.getBestBlockHash` RPC

---

packages/testcontainers/src/chains/defid_container.ts

update testcontainers to 1.7.1

---

packages/jellyfish-transaction/__tests__/script/defi/dftx_token/TokenUpdate.test.ts
packages/jellyfish-transaction/__tests__/script/defi/dftx_token/TokenUpdateAny.test.ts
packages/jellyfish-transaction/src/script/defi/dftx.ts
packages/jellyfish-transaction/src/script/defi/dftx_token.ts
packages/jellyfish-transaction/src/script/mapping.ts

/kind feature
Fixes part of #108

Add `DfTx` TokenUpdate, TokenUpdateAny

---

.github/workflows/release-publish.yml

fixed release script invalid semver

---

packages/jellyfish-api-core/__tests__/category/wallet.test.ts
packages/jellyfish-api-core/__tests__/category/wallet/dumpPrivKey.test.ts
packages/jellyfish-api-core/__tests__/category/wallet/importPrivkey.test.ts
packages/jellyfish-api-core/__tests__/category/wallet/wallet.test.ts
packages/jellyfish-api-core/src/category/wallet.ts
website/docs/jellyfish/api/wallet.md

/kind feature
RPC wallet implementation #48 
Fixes #

`wallet.dumpPrivKey` and `wallet.importPrivKey` RPC 

---

packages/testcontainers/src/chains/defid_container.ts

Update `@defichain/testcontainers` to 1.7.3

---

.gitignore
packages/jellyfish-transaction/__tests__/buffer/buffer_composer.test.ts
packages/jellyfish-transaction/__tests__/script/defi/dftx_pool/PoolUpdatePair.test.ts
packages/jellyfish-transaction/src/buffer/buffer_composer.ts
packages/jellyfish-transaction/src/script/defi/dftx.ts
packages/jellyfish-transaction/src/script/defi/dftx_pool.ts
packages/jellyfish-transaction/src/script/mapping.ts

/kind feature
Fixes part of #108

Add `DfTx` PoolUpdatePair

---

packages/jellyfish-api-core/__tests__/category/token/listTokens.test.ts

/kind fix
Fix fail test in listTokens RPC which happens occasionally.
Fixes #325

Fix failed test in listTokens RPC

---

packages/jellyfish-api-core/__tests__/category/blockchain/getChainTips.test.ts

/kind fix
Fix fail test in getChainTips RPC which happens occasionally.
Fixes #326

Fix failed test in getChainTips RPC

---

package.json
packages/jellyfish-api-core/__tests__/category/blockchain/getBlock.test.ts
packages/jellyfish-api-core/__tests__/category/blockchain/getBlockHash.test.ts
packages/jellyfish-api-core/__tests__/category/blockchain/getTxOut.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_appoint_oracle.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_liq_pool_remove_liquidity.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_remove_oracle.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_set_oracle_data.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_update_oracle.test.ts
packages/testcontainers/src/chains/defid_container.ts
packages/testing/__tests__/account.test.ts

QOL changes for jellyfish, see https://github.com/DeFiCh/ain/pull/464

Update `@defichain/testcontainers` with chainparams QOL changes

---

.github/CODEOWNERS
.idea/dictionaries/fuxing.xml

/kind chore
Updated CODEOWNERS to reflect recent contributing activity, this will automatically request individuals for reviews. Code cannot be merged without `CODEOWNERS` approval. This gives individuals ownership and responsibility for the code that are in this repository.

updated CODEOWNERS to reflect recent contributing activity

---

packages/jellyfish-api-core/__tests__/category/server/getRpcInfo.test.ts
packages/jellyfish-api-core/src/category/server.ts
packages/jellyfish-api-core/src/index.ts
website/docs/jellyfish/api/server.md
website/sidebars.js

/kind feature
Implemented RPC for #48
1. server.getrpcinfo
Fixes #

added getRpcInfo rpc

---

packages/jellyfish-api-core/__tests__/category/oracle/appointOracle.test.ts
packages/jellyfish-api-core/src/category/oracle.ts
packages/jellyfish-api-core/src/index.ts
website/docs/jellyfish/api/oracle.md
website/sidebars.js

/kind feature
Add appointoracle rpc

Add appointOracle RPC

---

packages/jellyfish-api-core/__tests__/category/server/upTime.test.ts
packages/jellyfish-api-core/__tests__/category/server/uptime.test.ts
packages/jellyfish-api-core/src/category/server.ts
website/docs/jellyfish/api/server.md

/kind feature
added getRpcInfo rpc
1. server.uptime
Fixes uptime in #48

Add uptime RPC

---

packages/jellyfish-api-core/__tests__/category/oracle/appointOracle.test.ts
packages/jellyfish-api-core/__tests__/category/oracle/removeOracle.test.ts
packages/jellyfish-api-core/src/category/oracle.ts
packages/jellyfish-api-core/src/index.ts
website/docs/jellyfish/api/oracle.md

/kind feature
Add removeOracle rpc

Add removeOracle rpc

---

packages/jellyfish-api-core/__tests__/category/account/accountHistoryCount.test.ts
packages/jellyfish-api-core/__tests__/category/account/listAccountHistory.test.ts
packages/jellyfish-api-core/src/category/account.ts
website/docs/jellyfish/api/account.md

/kind fix
Fixed issue with TxType filter in Account RPC
Fixes #252

Add Filter by DfTxType in AccountRPCs

---

packages/jellyfish-transaction/__tests__/script/index.test.ts
packages/jellyfish-transaction/__tests__/script/mapping.test.ts
packages/jellyfish-transaction/src/script/control.ts
packages/jellyfish-transaction/src/script/mapping.ts

/kind feature
Added OP_CODES 0x61-0x69

Control.ts OP_CODES (0x61-0x69)

---

packages/jellyfish-api-core/__tests__/category/wallet/getTransaction.test.ts
packages/jellyfish-api-core/src/category/wallet.ts
website/docs/jellyfish/api/wallet.md

/kind feature
Implemented RPC for #48 
1. wallet.gettransaction

Added getTransaction RPC

---

packages/jellyfish-api-core/__tests__/category/oracle/getOracleData.test.ts
packages/jellyfish-api-core/__tests__/category/oracle/setOracleData.test.ts
packages/jellyfish-api-core/src/category/oracle.ts
website/docs/jellyfish/api/oracle.md

/kind feature
Add getOracleData rpc

Add getOracleData rpc

---

website/sidebars.js

removed duplicated account in sidebar

---

README.md

update project ref readme

---

packages/jellyfish-wallet-mnemonic/__tests__/mnemonic/bip39.test.ts
packages/jellyfish-wallet-mnemonic/src/mnemonic.ts

/kind feature
For UI single mnemonic word validation.

added single word mnemonic validation

---

.github/CODEOWNERS

/kind chore
Updated CODEOWNERS due to recent activity from @ivan-zynesis and @canonbrother

CODEOWNERS updates @ivan-zynesis and @canonbrother

---

packages/testcontainers/README.md
packages/testcontainers/__tests__/chains/reg_test_container/coinbase.test.ts
packages/testcontainers/__tests__/chains/reg_test_container/index.test.ts
packages/testcontainers/__tests__/chains/reg_test_container/masternode.test.ts
packages/testcontainers/__tests__/chains/reg_test_container/persistent.test.ts
packages/testcontainers/__tests__/index.test.ts
packages/testcontainers/src/chains/defid_container.ts
website/docs/testcontainers/usage.md

/kind feature
`getMintingInfo()` has been deprecated.
Fixes #376 
Fixed documentation.

Add getMiningInfo to DeFiDContainer

---

package-lock.json
package.json

/kind chore
To silent @dependabot false update notices.

fix package-lock.json to silent updates

---

packages/testing/__tests__/poolpair.test.ts
packages/testing/src/poolpair.ts

/kind feature
Add poolSwap and listPoolPairs utils

Add `poolSwap` and `listPoolPairs` in defi/testing

---

.idea/dictionaries/fuxing.xml
packages/jellyfish-api-core/__tests__/category/rawtx/getRawTransaction.test.ts
packages/jellyfish-api-core/src/category/blockchain.ts
packages/jellyfish-api-core/src/category/rawtx.ts
website/docs/jellyfish/api/blockchain.md
website/docs/jellyfish/api/rawtx.md

/kind feature
Add getRawTransaction rpc
Fixes part of  #48

Add getRawTransaction rpc

---

packages/jellyfish-api-core/__tests__/category/account/accountHistoryCount.test.ts

/kind fix
Flaky test in accountHistoryCount test
Fixes #338

Fixed flaky test in accounthistory

---

website/docs/jellyfish/api/wallet.md

/kind docs
Corrected a typo in wallet documentation
Fixes #

Fixed wallet documentation typo

---

packages/jellyfish-api-core/__tests__/category/wallet/getBalances.test.ts
packages/jellyfish-api-core/src/category/wallet.ts
website/docs/jellyfish/api/wallet.md

/kind feature
Implemented RPC for #48 
1. wallet.getbalances

Added getBalances RPC

---

packages/jellyfish-api-core/__tests__/category/poolpair/testpoolswap.test.ts
packages/jellyfish-api-core/src/category/poolpair.ts
packages/testing/src/token.ts
website/docs/jellyfish/api/poolpair.md

/kind feature
Add testpoolswap rpc 

Add `testpoolswap` RPC

---

packages/jellyfish-api-core/__tests__/category/masternode/createMasternode.test.ts
packages/jellyfish-api-core/__tests__/category/masternode/getMasternode.test.ts
packages/jellyfish-api-core/__tests__/category/masternode/listMasternodes.test.ts
packages/jellyfish-api-core/src/category/masternode.ts
packages/jellyfish-api-core/src/index.ts
website/docs/jellyfish/api/masternode.md
website/sidebars.js

/kind feature
Masternode RPC implementation #48 

Masternode RPC (createmasternode, listmasternodes, getmasternode)

---

packages/jellyfish-transaction/__tests__/script/index.test.ts
packages/jellyfish-transaction/__tests__/script/mapping.test.ts
packages/jellyfish-transaction/src/script/bitwise.ts
packages/jellyfish-transaction/src/script/mapping.ts

/kind feature 
Adds opcodes for biwise mentioned in #107 
Fixes part of #107

Add bitwise OP CODES.

---

packages/jellyfish-api-core/__tests__/category/masternode/resignMasternode.test.ts
packages/jellyfish-api-core/src/category/masternode.ts
website/docs/jellyfish/api/masternode.md

/kind feature
Added resignMasternode rpc

Added `resignMasternode` RPC

---

packages/jellyfish-api-core/__tests__/category/poolpair/testpoolswap.test.ts
packages/jellyfish-api-core/src/category/poolpair.ts
website/docs/jellyfish/api/poolpair.md

/kind fix
`testpoolswap` markdown fixes and some minor changes on #411

testpoolswap markdown fixes

---

README.md
packages/jellyfish/__tests__/cjs.test.ts
packages/jellyfish/__tests__/export_const.test.ts
packages/jellyfish/__tests__/export_default.test.ts
packages/jellyfish/src/index.ts
packages/jellyfish/src/provider.ts
website/docs/jellyfish/usage.md
website/docusaurus.config.js

/kind docs
updated *.MD and packages/jellyfish to reflect current project direction
- docs hosted on https://jellyfish.defichain.com
- removed ocean from packages/jellyfish, will be introduced in DeFiCh/whale project instead
- updated tagline, announcement and URL for docs website
Fixes #427

updated `*.MD` and packages/jellyfish to reflect current project direction

---

packages/jellyfish-api-core/__tests__/category/icxorderbook/createOrder.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/makeOffer.test.ts
packages/jellyfish-api-core/src/category/icxorderbook.ts
website/docs/jellyfish/api/icxorderbook.md

/kind feature 
This PR will interface `icx_makeoffer` RPC to jellyfish
Fixes #
depends on #398

Interface `icx_makeoffer` RPC

---

.github/CODEOWNERS
.idea/dictionaries/fuxing.xml

/kind chore
Updated CODEOWNERS to reflect recent contributing activity, this will automatically request individuals for reviews. Code cannot be merged without `CODEOWNERS` approval. This gives individuals ownership and responsibility for the code that is in this repository.
- @ivan-zynesis removed from ICX code owner to focus on products
- @ivan-zynesis added to overall `jellyfish-api-core` due to recent reviewing activity.
- @siradji and @aikchun added to `jellyfish-api-core` and `website`

added @ivan-zynesis @siradji @aikchun to `jellyfish-api-core` CODEOWNERS

---

packages/jellyfish-api-core/__tests__/category/icxorderbook/closeOffer.test.ts
packages/jellyfish-api-core/src/category/icxorderbook.ts
website/docs/jellyfish/api/icxorderbook.md

/kind feature
This PR will interface `icx_closeoffer` RPC to jellyfish
Fixes #
depends on #399

Interface `icx_closeoffer` RPC

---

packages/jellyfish-api-core/__tests__/category/icxorderbook/getOrder.test.ts
packages/jellyfish-api-core/src/category/icxorderbook.ts
website/docs/jellyfish/api/icxorderbook.md

/kind feature
This PR will interface `icx_getorder` RPC to jellyfish
Fixes #
depends on #400

Interface `icx_getorder` RPC

---

.github/workflows/ci.yml

setup-node now support cache, removed old workflow cache

setup-node now support cache, removed old workflow cache

---

packages/jellyfish-api-core/__tests__/category/icxorderbook/closeOffer.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/icx_setup.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/listOrders.test.ts
packages/jellyfish-api-core/src/category/icxorderbook.ts
website/docs/jellyfish/api/icxorderbook.md

/kind feature
This PR will interface `icx_listorders` RPC to jellyfish
Fixes #
depends on #401

Interface `icx_listorders` RPC

---

packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_dex_poolswap.test.ts

/kind feature
Added tests for maxPrice in `txn_builder_dex_poolswap`
Fixes #417

added maxPrice tests for `txn_builder_dex_poolswap`

---

packages/jellyfish-api-core/__tests__/category/icxorderbook/closeOffer.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/createOrder.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/getOrder.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/icx_setup.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/listOrders.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/makeOffer.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/submitDFCHTLC.test.ts
packages/jellyfish-api-core/src/category/icxorderbook.ts
website/docs/jellyfish/api/icxorderbook.md

/kind feature
This PR will interface`icx_submitdfchtlc` RPC to jellyfish
Fixes #
depends on #402

Interface `icx_submitdfchtlc` RPC

---

packages/jellyfish-api-core/__tests__/category/icxorderbook/icx_setup.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/submitExtHTLC.test.ts
packages/jellyfish-api-core/src/category/icxorderbook.ts
website/docs/jellyfish/api/icxorderbook.md

/kind feature
This PR will interface `icx_submitexthtlc` RPC to jellyfish
Fixes #
depends on #404

Interface `icx_submitexthtlc` RPC

---

packages/jellyfish-api-core/__tests__/category/icxorderbook/claimDFCHTLC.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/icx_setup.ts
packages/jellyfish-api-core/src/category/icxorderbook.ts
website/docs/jellyfish/api/icxorderbook.md

/kind feature
This PR will interface `icx_claimdfchtlc` RPC to jellyfish
Fixes #
depends on #405

Interface`icx_claimdfchtlc` RPC

---

.github/CODEOWNERS
jest.config.js
packages/jellyfish-wallet-classic/README.md
packages/jellyfish-wallet-classic/__tests__/wallet_classic.test.ts
packages/jellyfish-wallet-classic/jest.config.js
packages/jellyfish-wallet-classic/package.json
packages/jellyfish-wallet-classic/src/classic.ts
packages/jellyfish-wallet-classic/src/index.ts
packages/jellyfish-wallet-classic/tsconfig.build.json
tsconfig.build.json
tsconfig.json
website/docs/introduction.md

/kind feature
WalletClassic implements a simple, single elliptic pair wallet.
Fixes #452

`jellyfish-wallet-classic`

---

packages/jellyfish-api-core/__tests__/category/icxorderbook/listHTLCs.test.ts
packages/jellyfish-api-core/src/category/icxorderbook.ts
website/docs/jellyfish/api/icxorderbook.md

/kind feature 
This PR will interface`icx_listhtlcs` RPC to jellyfish
Fixes #
depends on #406

Interface `icx_listhtlcs` RPC

---

packages/jellyfish-api-core/__tests__/category/masternode/getGov.test.ts
packages/jellyfish-api-core/__tests__/category/masternode/setGov.test.ts
packages/jellyfish-api-core/src/category/masternode.ts
packages/jellyfish-api-core/src/category/poolpair.ts
website/docs/jellyfish/api/masternode.md
website/docs/jellyfish/api/poolpair.md

/kind feature
added `setGov` and `getGov` rpc

Add `getGov` and `setGov` RPC

---

packages/jellyfish-api-core/__tests__/category/icxorderbook/closeOrder.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/listHTLCs.test.ts
packages/jellyfish-api-core/src/category/icxorderbook.ts
website/docs/jellyfish/api/icxorderbook.md

/kind feature 
This PR will interface `icx_closeorder` RPC to jellyfish
Fixes #
depends on #407

Interface`icx_closeorder` RPC 

---

packages/jellyfish-api-core/__tests__/category/icxorderbook/complexTests.test.ts

/kind feature 
Adds some complex tests for ICX
Fixes #
depends on #408

Add complex tests for ICX

---

packages/jellyfish-api-core/__tests__/category/icxorderbook/claimDFCHTLC.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/closeOffer.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/closeOrder.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/complexTests.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/getOrder.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/listHTLCs.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/listOrders.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/makeOffer.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/submitDFCHTLC.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/submitExtHTLC.test.ts
packages/testcontainers/src/chains/defid_container.ts

/kind refactor
This will enable all ICX tests.
Tests are refactored as per minimum timeout for ICX on C++ side
Fixes #
depends #450

Enable all ICX tests on 1.8.x

---

packages/jellyfish-api-core/__tests__/category/account/listAccountHistory.test.ts

Assert with expect.arrayContaining and expect.objectContaining to check for correctness in tests.

---

.github/CODEOWNERS
.idea/jellyfish.iml

CODEOWNERS rename proposal to governance

---

packages/jellyfish-api-core/__tests__/category/poolpair/poolSwapMaxPrice.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_dex_poolswap.test.ts
packages/jellyfish-transaction/__tests__/buffer/buffer_composer.test.ts
packages/jellyfish-transaction/__tests__/script/dftx/dftx_pool/PoolSwap.test.ts
packages/jellyfish-transaction/src/buffer/buffer_composer.ts
packages/jellyfish-transaction/src/script/dftx/dftx_pool.ts

/kind fix
Automatic Conversion of Integer/Fraction for MaxPrice in dftx_pool.ts
Fixes #439

Automatic Conversion of Integer/Fraction for MaxPrice in dftx_pool.ts

---

packages/jellyfish-wallet-encrypted/__tests__/bip32.test.ts
packages/jellyfish-wallet-encrypted/__tests__/provider/scrypt_simple.test.ts
packages/jellyfish-wallet-encrypted/__tests__/scrypt.test.ts
packages/jellyfish-wallet-encrypted/src/hd_node.ts
packages/jellyfish-wallet-encrypted/src/provider/scrypt_provider.ts
packages/jellyfish-wallet-encrypted/src/provider/scrypt_simple.ts
packages/jellyfish-wallet-encrypted/src/scrypt.ts

/kind fix
Light wallet implementation required interfaces
Fixes #

Minor improvement to ease integration

---

packages/testcontainers/__tests__/chains/reg_test_container/spv.test.ts
packages/testcontainers/src/chains/reg_test_container/index.ts
packages/testcontainers/src/chains/reg_test_container/spv.ts

/kind feature
Adds SPV testing functionnalities
Fixes #218

Added RegTestContainer SPV testing functionnalities

---

.github/CODEOWNERS

added @canonbrother to testcontainers
/kind chore

reduced api-core codeowners complexity

---

packages/jellyfish-api-core/__tests__/category/spv/getNewAddress.test.ts
packages/jellyfish-api-core/src/category/spv.ts
packages/jellyfish-api-core/src/index.ts
website/docs/jellyfish/api/spv.md
website/sidebars.js

/kind feature
Adds SPV getNewAddress RPC
Fixes part of  #202

Added SPV getNewAddress RPC

---

packages/jellyfish-api-core/__tests__/category/account/listBurnHistory.test.ts
packages/jellyfish-api-core/__tests__/category/oracle/getPrice.test.ts
packages/jellyfish-api-core/__tests__/category/oracle/listLatestRawPrices.test.ts
packages/jellyfish-api-core/__tests__/category/oracle/listPrices.test.ts
packages/jellyfish-api-core/__tests__/category/oracle/setOracleData.test.ts
packages/jellyfish-api-core/src/category/oracle.ts

/kind chore
Update failing tests to support https://github.com/DeFiCh/ain/issues/513
Fixes #

Updated  failing oracle tests to support ain/513

---

.idea/dictionaries/fuxing.xml
packages/jellyfish-api-core/__tests__/category/account/listBurnHistory.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/claimDFCHTLC.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/closeOffer.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/closeOrder.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/complexTests.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/getOrder.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/listHTLCs.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/listOrders.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/makeOffer.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/submitDFCHTLC.test.ts
packages/jellyfish-api-core/__tests__/category/icxorderbook/submitExtHTLC.test.ts
packages/jellyfish-api-core/__tests__/category/mining/getMiningInfo.test.ts
packages/jellyfish-api-core/__tests__/category/oracle/appointOracle.test.ts
packages/jellyfish-api-core/__tests__/category/oracle/getPrice.test.ts
packages/jellyfish-api-core/__tests__/category/oracle/listLatestRawPrices.test.ts
packages/jellyfish-api-core/__tests__/category/oracle/listPrices.test.ts
packages/jellyfish-api-core/__tests__/category/oracle/setOracleData.test.ts
packages/jellyfish-api-core/__tests__/category/oracle/updateOracle.test.ts
packages/jellyfish-api-core/src/category/mining.ts
packages/jellyfish-api-core/src/category/oracle.ts
packages/testcontainers/src/chains/defid_container.ts
packages/testcontainers/src/chains/reg_test_container/index.ts

Bump `@defichain/testcontainers` to support `v1.8.0`.

Bump DeFiCh/ain to `v1.8.0`

---

.github/CODEOWNERS

extending spv CODEOWNERS to icx CODEOWNERS

---

.idea/dictionaries/fuxing.xml
packages/jellyfish-api-core/__tests__/category/account/getBurnInfo.test.ts
packages/jellyfish-api-core/src/category/account.ts
website/docs/jellyfish/api/account.md

/kind feature
Implemented `getBurnInfo` RPC.

added `getBurnInfo` RPC

---

packages/testcontainers/package.json
packages/testcontainers/src/chains/defid_container.ts
packages/testcontainers/src/chains/reg_test_container/masternode.ts
packages/testcontainers/src/chains/reg_test_container/masternode_group.ts

fix `waitForRpc` for better stability

---

packages/jellyfish-api-core/src/category/account.ts
packages/jellyfish-api-core/src/category/token.ts
website/docs/jellyfish/api/account.md
website/docs/jellyfish/api/token.md

/kind fix
```diff
- type TokenRegexType = `${number}@${string}`
```
- This is a new feature that is added very recently, not all typescript projects support it. E.g. `DeFiCh/wallet`
- Doesn't work well with dynamic variable construction

removed template interface in `jellyfish-api-core`

---

package-lock.json
package.json
packages/testcontainers/package.json

Bump jest and ts-jest from 26.x to 27.0.x

---

packages/jellyfish-api-core/__tests__/category/spv/decodeHtlcScript.test.ts
packages/jellyfish-api-core/src/category/spv.ts
website/docs/jellyfish/api/spv.md

/kind feature
Adds SPV decodeHtlcScript RPC

Added SPV decodeHtlcScript RPC

---

packages/jellyfish-api-core/__tests__/category/spv/claimHtlc.test.ts
packages/jellyfish-api-core/src/category/spv.ts
website/docs/jellyfish/api/spv.md

/kind feature
Adds SPV claimHtlc RPC

Added SPV claimHtlc RPC

---

packages/jellyfish-api-core/__tests__/category/account/getAccount.test.ts
packages/jellyfish-api-core/__tests__/category/token/listTokens.test.ts

added more testing to getAccount and listTokens to match whale usage pattern

---

.github/CODEOWNERS
.idea/dictionaries/fuxing.xml

/kind chore
Some of the PRs are not yet merged by the added CODEOWNERS have already started working on them.

updated CODEOWNERS with recent contributing activities

---

packages/jellyfish-api-core/src/index.ts

/kind fix
Export icxorderbook from jellyfish-api-core.
Fixes #

Export icxorderbook from jellyfish-api-core.

---

packages/jellyfish-api-core/__tests__/category/spv/refundHtlc.test.ts
packages/jellyfish-api-core/src/category/spv.ts
website/docs/jellyfish/api/spv.md

/kind feature
Adds SPV refundHtlc RPC

Added SPV refundHtlc RPC

---

packages/jellyfish-crypto/__tests__/elliptic.test.ts
packages/jellyfish-crypto/src/aes256.ts
packages/jellyfish-crypto/src/elliptic.ts
packages/jellyfish-wallet-encrypted/src/encryption.ts
packages/jellyfish-wallet-mnemonic/src/mnemonic.ts

/kind feature
- Added Elliptic.generate() for EllipticPair generation
- Also refactored/cleanup rng implementation

added `Elliptic.generate()` for EllipticPair generation

---

packages/jellyfish-testing/__tests__/icxorderbook.test.ts
packages/jellyfish-testing/src/icxorderbook.ts
packages/jellyfish-testing/src/index.ts

/kind feature
Adds ICX setup and testing functionnalities to jellyfish-testing

Adds ICX to jellyfish-testing

---

packages/jellyfish-api-core/__tests__/category/spv/listHtlcsOutputs.test.ts
packages/jellyfish-api-core/__tests__/category/spv/refundHtlc.test.ts
packages/jellyfish-api-core/src/category/spv.ts
website/docs/jellyfish/api/spv.md

/kind feature
Adds listHtlcOutputs RPC
Fixes #202 (last issue in the series)

Added listHtlcOutputs RPC

---

packages/jellyfish-api-core/__tests__/category/governance/governance_container.ts
packages/jellyfish-api-core/__tests__/category/governance/listVotes.test.ts
packages/jellyfish-api-core/src/category/governance.ts
website/docs/jellyfish/api/governance.md

/kind feature
Added listVotes RPC
Fixes part of #458

Added listVotes RPC

---

packages/jellyfish-api-core/__tests__/category/misc/setMockTime.test.ts
packages/jellyfish-api-core/src/category/misc.ts
packages/jellyfish-api-core/src/index.ts
website/docs/jellyfish/api/misc.md

/kind feature
add mock time rpc for testing purpose

Add setMockTime rpc

---

.github/CODEOWNERS

consolidating jellyfish core code owners

---

packages/jellyfish-wallet-encrypted/README.md
packages/jellyfish-wallet-encrypted/src/hd_node.ts
packages/jellyfish-wallet-mnemonic/README.md
packages/jellyfish-wallet-mnemonic/src/hd_node.ts

/kind docs
Updated the narrative of jellyfish-wallet with the latest information.

updated the narrative of jellyfish-wallet with the latest context

---

.idea/dictionaries/fuxing.xml
package-lock.json
packages/testcontainers/package.json
packages/testcontainers/src/chains/defid_container.ts
packages/testcontainers/src/chains/reg_test_container/container_group.ts
website/package-lock.json
website/package.json

updated testcontainers to use cross-fetch for consistency across packages

---

packages/jellyfish-api-core/__tests__/category/loan/listCollateralTokens.test.ts
packages/jellyfish-api-core/__tests__/category/loan/loan_container.ts
packages/jellyfish-api-core/__tests__/category/loan/setCollateralToken.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/loan_container.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_loan_set_collateral_token.test.ts

/kind feature
CollateralToken's priceFeed should contain USD price
Fixes #646

CollateralToken's priceFeed should contain USD price

---

packages/jellyfish-api-core/__tests__/category/masternode/getActiveMasternode.test.ts
packages/jellyfish-api-core/src/category/masternode.ts
website/docs/jellyfish/api/masternode.md

/kind feature
Added `getActiveMasternodeCount` RPC

Added `getActiveMasternodeCount` RPC

---

jest.config.js

simplify `jest.config.js` to use regex capture

---

.github/dependabot.yml
.gitignore

set dependabot update schedule to daily from weekly to further shift left deps update timeline

---

docs/node/RPC Category/16-loan.md
packages/jellyfish-api-core/src/category/loan.ts

Fix small bug in listLoanTokens and listCollateralTokens RPCs

---

packages/jellyfish-api-core/__tests__/category/loan/depositToVault.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/loan_container.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_loan_deposit_to_vault.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_loan_set_collateral_token.test.ts
packages/jellyfish-transaction-builder/src/txn/txn_builder_loans.ts
packages/jellyfish-transaction/__tests__/script/dftx/dftx_balance/TokenBalance.test.ts
packages/jellyfish-transaction/__tests__/script/dftx/dftx_loans/DepositToVault.test.ts
packages/jellyfish-transaction/src/script/dftx/dftx.ts
packages/jellyfish-transaction/src/script/dftx/dftx_balance.ts
packages/jellyfish-transaction/src/script/dftx/dftx_loans.ts
packages/jellyfish-transaction/src/script/mapping.ts

/kind feature 
Add depositToVault dftx
Fixes part of #532

Added depositToVault dftx to transaction builder.

---

packages/jellyfish-api-core/src/category/account.ts

/kind docs
- To fix typo of `UXTO` in `accountToUtxos()`

Fix typo in comment

---

docs/node/RPC Category/16-loan.md
packages/jellyfish-api-core/src/category/loan.ts

/kind fix
Supposed to be `index: number`, not `index: BigNumber`

fix wrong number Batch interface for Liquidated Vault

---

packages/jellyfish-api-core/__tests__/category/governance/governance_container.ts
packages/jellyfish-transaction/__tests__/script/dftx/dftx_governance/CreateCfp.test.ts
packages/jellyfish-transaction/src/script/dftx/dftx_governance.ts

/kind fix
createCfp shared the same opcode (letter e) with closeVault.
Assign new letter to createCfp
Fixes #

Change letter e to P for createCfp

---

packages/jellyfish-api-core/__tests__/category/loan/takeLoan.test.ts

/kind feature
Extra condition check in consensus now, add corresponding test case
Fixes #

Extra `takeLoan` collateral % check test case

---

.github/workflows/ci.yml
jest.config.js
jest.sequencer.js
package-lock.json
package.json

/kind chore
With tests taking up to 1 hour to complete, it's getting too ridiculous to wait for tests to complete. This PR adds a non-optimal parallelization of tests across 6 instances via deterministic random sorting of test files. This drastically reduces the testing duration by 4x.
- **Non-optimal parallelization:** time taken to run each test instance is non-uniform and not the same for each instance with drastic differences.
- **Optimal parallelization:** time taken to run each test instance is uniform and the same for each instance.

add non optimal parallelization across 6 instances

---

packages/jellyfish-api-core/__tests__/category/loan/closeVault.test.ts
packages/jellyfish-api-core/__tests__/category/loan/updateVault.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_loan_close_vault.test.ts
packages/testcontainers/src/containers/RegTestContainer/Masternode.ts

/kind fix
1. Fix flanky test. (See https://github.com/DeFiCh/jellyfish/runs/4142447619?check_suite_focus=true#step:5:3782)
2. Change timeout from 100,000 to 30,000 ms for WaitFor functions.
3. activePrice / nextPrice should be parsed as string. (See https://github.com/DeFiCh/jellyfish/pull/731#discussion_r744466882)
Fixes #

Fix flaky test and update timeout / type for waitfor functions

---

.eslintrc
packages/jellyfish-block/src/block.ts
packages/testcontainers/src/containers/RegTestContainer/Masternode.ts

/kind chore
https://github.com/DeFiCh/jellyfish/pull/816#discussion_r745355804

add no-else-return eslint rule

---

packages/jellyfish-api-core/__tests__/category/loan/loan_container.ts
packages/jellyfish-transaction-builder/__tests__/txn/loan_container.ts
packages/testcontainers/__tests__/containers/Container.test.ts
packages/testcontainers/__tests__/containers/RegTestContainer/Coinbase.test.ts
packages/testcontainers/__tests__/containers/RegTestContainer/ContainerGroup.test.ts
packages/testcontainers/__tests__/containers/RegTestContainer/Masternode.test.ts
packages/testcontainers/__tests__/containers/RegTestContainer/Persistent.test.ts
packages/testcontainers/__tests__/containers/RegTestContainer/SPV.test.ts
packages/testcontainers/__tests__/containers/RegTestContainer/index.test.ts
packages/testcontainers/__tests__/index.test.ts
packages/testcontainers/src/containers/DeFiDContainer.ts
packages/testcontainers/src/containers/RegTestContainer/LoanContainer.ts

- Bump to DeFiCh/ain `2.1.0` release
- Also replaced deprecated method in test

Bump to latest defid 2.1.0 release

---

docs/node/RPC Category/11-masternode.md
packages/jellyfish-api-core/__tests__/category/masternode/listGovs.test.ts
packages/jellyfish-api-core/__tests__/category/masternode/setGov.test.ts
packages/jellyfish-api-core/__tests__/category/masternode/setGovHeight.test.ts
packages/jellyfish-api-core/src/category/masternode.ts

/kind feature
New RPC in FC
Fixes #
Doing both RPC together, only `setGovHeight` will cause significant change in `listGovs` result

RPC: `setGovHeight` and `listGovs`

---

packages/jellyfish-api-core/__tests__/category/loan/takeLoan.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_loan_take_loan.test.ts
packages/testcontainers/src/containers/RegTestContainer/LoanContainer.ts

/kind refactor
/kind feature
Added vault.state test on takeLoan
Added no live fixed price test
Added test exceed collateral ratio by taking multi loans 
Added liquidated by interest
Added vault.batches splitting value after liquidation on taking multiple loans
Refactored takeLoan rpc and txn builder

Add vault.state testing on takeLoan + some refactors

---

packages/testcontainers/src/containers/DeFiDContainer.ts

Bump defid from 2.1.0 to 2.2.0

---

packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_governance_setgov.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_governance_setgovheight.test.ts
packages/jellyfish-transaction-builder/src/txn/txn_builder_governance.ts
packages/jellyfish-transaction/__tests__/script/dftx/dftx_governance/SetGovernanceHeight.test.ts
packages/jellyfish-transaction/src/script/dftx/dftx.ts
packages/jellyfish-transaction/src/script/dftx/dftx_governance.ts
packages/jellyfish-transaction/src/script/mapping.ts
packages/testcontainers/src/containers/RegTestContainer/ContainerGroup.ts

/kind feature
New DfTx type in FC
Fixes part of #532 
Not txn-builder is added as it is only for foundation (same for `setGov`), solely for decoding purpose.

DfTx: `setGovHeight`

---

docs/node/RPC Category/06-poolpair.md
packages/jellyfish-api-core/src/category/poolpair.ts

/kind fix
Update type of status for poolpairs. Related to https://github.com/DeFiCh/whale/pull/584
Fixes #

fix poolpair wrong type for status

---

codecov.yml

add codecov.yml to allow diff threshold of 1%

---

.github/workflows/ci.yml

/kind chore
Increased parallelization of `ci.yml` for faster development cycle.

increased ci.yml tests parallelization from 6 to 8

---

packages/jellyfish-transaction-builder/src/txn/txn_builder_loans.ts

/kind fix
On RegTest, the fee is 1 DFI, on MainNet it's 2 DFI.

fix createVault MainNet fee creation

---

packages/jellyfish-api-core/__tests__/category/loan/closeVault.test.ts
packages/jellyfish-api-core/__tests__/category/loan/paybackLoan.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_dex_compositeswap.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_loan_close_vault.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_loan_payback_loan.test.ts
packages/testcontainers/src/containers/RegTestContainer/LoanContainer.ts

/kind fix
1. DUSD fixture correction
old: set DUSD token as normal token and minted
new: set DUSD token as loan token and should own DUSD from `takeLoan`
2. test paybackLoan with DUSD
3. test zero interest

Fix DUSD related fixture

---

docs/ocean/01-overview.md

additional note on minor versioned endpoint for ocean

---

packages/testcontainers/src/containers/DeFiDContainer.ts

Bump DeFiDContainer to 2.2.1

---

packages/jellyfish-wallet/src/wallet.ts

Add wallet purpose `PURPOSE_LIGHT_PRICE_ORACLE`

---

README.md
docs/ecosystem/01-introduction.md

/kind docs
Include border for better compatibility with markdown parser.

fix table in markdowns

---

packages/jellyfish-api-core/__tests__/category/loan/placeAuctionBid.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_loan_place_auction_bid.test.ts

/kind chore
Expecting new behaviour on test or may have bug

Set up require pools on bid test

---

docs/ocean/01-overview.mdx
docs/ocean/REFERENCES/address.mdx
docs/ocean/REFERENCES/oracles.mdx
docs/ocean/REFERENCES/prices.mdx

/kind docs
add oracles and prices docs for Ocean API
Fixes #873

add oracles and prices docs for Ocean API

---

.github/workflows/ci.yml

/kind chore
To prepare for consolidation efforts with increased test conslidation.

increase ci test parallelization to 10 for faster PR cycle

---

.github/workflows/ci.yml
.github/workflows/release-publish.yml
netlify.toml
package-lock.json
package.json

Fix broken publish workflow, also added `all:` prefix to all scripts running in all workspaces for better clarity of execution.

chore(workflow): fix and optimize publish workflow

---

.github/labeler.yml

Add `kind/dependencies` via regex "^deps(\\(.+\\))?: .+".

chore(workflow): add kind/dependencies title matcher

---

.github/dependabot.yml
.github/labeler.yml

chore(workflow): add dependabot semantic pr with scope

---

apps/website/package.json
package-lock.json

To prevent collision and keep consistency across the ecosystem.

chore(apps): update website package name to @defichain-apps/website

---

packages/jellyfish-api-core/__tests__/category/governance/governance_container.ts
packages/jellyfish-api-core/__tests__/category/loan/getInterest.test.ts
packages/jellyfish-api-core/__tests__/category/loan/getLoanInfo.test.ts
packages/jellyfish-api-core/__tests__/category/loan/getVault.test.ts
packages/jellyfish-api-core/__tests__/category/loan/listAuctons.test.ts
packages/jellyfish-api-core/__tests__/category/loan/paybackLoan.test.ts
packages/jellyfish-api-core/__tests__/category/loan/placeAuctionBid.test.ts
packages/jellyfish-api-core/__tests__/category/loan/takeLoan.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_loan_payback_loan.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_loan_place_auction_bid.test.ts
packages/testcontainers/src/containers/DeFiDContainer.ts
packages/testcontainers/src/containers/RegTestContainer/index.ts

fix(core): interest update regression post `ain:2.3.x` update

---

.github/dependabot.yml
package-lock.json

For Semantic Pull Request title validation.

chore(workflow): add missing commit-message settings for dependabot

---

packages/jellyfish-api-core/__tests__/category/loan/paybackLoan.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_loan_payback_loan.test.ts

fix(packages): flaky vault state on paybackloan test

---

docs/node/CATEGORIES/11-masternode.md
packages/jellyfish-api-core/__tests__/category/masternode/getAnchorTeams.test.ts
packages/jellyfish-api-core/src/category/masternode.ts
packages/jellyfish-testing/src/testing.ts

Added getAnchorTeams rpc to rpc_masternode
Fixes # https://github.com/DeFiCh/jellyfish/issues/48

feat(jellyfish-api-core): add getAnchorTeams to rpc_masternode

---

.github/CODEOWNERS

Reshuffle CODEOWNERS into their SIG with new packages and contributors added.

chore(governance): reshuffle CODEOWNERS with new packages and contributors

---

packages/jellyfish-api-core/__tests__/category/loan/takeLoan.test.ts
packages/jellyfish-transaction-builder/src/txn/txn_builder.ts
packages/jellyfish-transaction-builder/src/txn/txn_builder_loans.ts

fix(jellyfish-transaction-builder): vault creation fee correction

---

docs/ocean/REFERENCES/address.mdx

The Ocean REST API is not fully documented. I added some more endpoints which can be used to get information on the defichain
Fixes #

docs(whale-api-client): Token Balances & Vault for `/address/` endpoint

---

docs/node/CATEGORIES/16-loan.md
packages/jellyfish-api-core/__tests__/category/loan/getInterest.test.ts
packages/jellyfish-api-core/__tests__/category/loan/paybackLoan.test.ts
packages/jellyfish-api-core/src/category/loan.ts
packages/testcontainers/src/containers/DeFiDContainer.ts

chore(packages/jellyfish-api-core): Add support for realizedInterestPerBlock

---

packages/jellyfish-network/src/index.ts

chore(jellyfish-network): export BlockSubsidy and BlockRewardDistribution

---

docs/node/CATEGORIES/08-account.md
packages/jellyfish-api-core/src/category/account.ts

Added `auctionburn` to BurnInfo

chore(jellyfish-api-core): Added `auctionburn` to burninfo

---

.github/workflows/release-publish.yml

Shift left release flow for turning our apps into docker containers.
Partially Fixes #943
Since we need to target `linux/arm64` docker build times are substantially increasing build times from a few minutes to an hour. 
Still looking into `arm64` build performance.

feat(docker): add docker release workflow

---

docs/node/CATEGORIES/01-blockchain.md
packages/jellyfish-api-core/__tests__/category/blockchain/getChainTxStats.test.ts
packages/jellyfish-api-core/src/category/blockchain.ts

/kind feature
Implemented type for RPC: #48
1. blockchain.getChainTxStats()

feat(jellyfish-api-core): add blockchain getChainTxStats RPC

---

packages/jellyfish-transaction/src/script/dftx/dftx_account.ts

Minor fixes on the typo in the comments for `dftx_account.ts`
Fixes #1091

docs(jellyfish-transaction): fix `dftx_account` class comments typo

---

docs/ocean/REFERENCES/poolpairs.mdx

chore(doc): add list and get poolpair API doc

---

apps/package.json

fix(apps): disable nest-apps from being published into npm

---

apps/legacy-api/__tests__/controllers/PoolPairController.test.ts
apps/legacy-api/src/controllers/PoolPairController.ts
apps/package.json

Implementation of legacy-api to remap the legacy API (https://api.defichain.com/v1/listswaps).
Which issue(s) does this PR fixes?:
Fixes part of https://github.com/DeFiCh/jellyfish/issues/1024

feat(apps/legacy-api): Legacy API - listswaps

---

apps/legacy-api/__tests__/controllers/NetworkParamValidation.test.ts
apps/legacy-api/__tests__/controllers/StatsController.test.ts
apps/legacy-api/src/controllers/stats/LegacyStatsProvider.ts
apps/legacy-api/src/controllers/stats/StatsController.ts
apps/legacy-api/src/modules/ControllerModule.ts

Implementation of legacy-api to remap the legacy stats API (https://api.defichain.com/v1/stats).
Which issue(s) does this PR fixes?:
Fixes part of https://github.com/DeFiCh/jellyfish/issues/1024

feat(apps/legacy-api): Legacy API - stats

---

packages/testcontainers/src/index.ts

chore(testcontainers): export `waitForCondition`

---

.github/CODEOWNERS

Updating CODEOWNERS to reflect recent participation for reviewers automation. This list is not exhaustive nor 100% accurate. It's done with top of mind recall and eyeballing recent commits.

chore(workflow): update CODEOWNERS to reflect recent participation

---

docs/legacy/01-endpoints.md

Add /stats endpoint documentation
Originally mentioned in https://github.com/DeFiCh/jellyfish/pull/1131#issuecomment-1055209282

chore(apps/legacy-api): add /stats documentation

---

.github/workflows/release-apps.yml

Forgot to remove an if check in previous PR:
- https://github.com/DeFiCh/jellyfish/pull/1085
Need to remove this or workflow will not trigger when we merge to main or perform a release.

fix(workflow): remove app release if check

---

.github/workflows/release-apps.yml

Adds playground api to the docker publish workflow
Fixes #1152

feat(workflow): add playground-api

---

packages/playground-api-client/src/index.ts

fix(apps): expose pg rpc client

---

apps/legacy-api/src/controllers/PoolPairController.ts

Fixed iterator next token. It should reset after iterating through all transactions.

fix(apps/legacy/getsubgraphswaps): iterator next token

---

docs/ocean/REFERENCES/poolpairs.mdx

docs(apps/ocean): Add List Pool Swaps API docs

---

packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_dex_compositeswap.test.ts

chore(packages): txn builder composite swap max price testing

---

apps/legacy-api/__tests__/controllers/PoolPairController.test.ts
apps/legacy-api/src/controllers/PoolPairController.ts
apps/legacy-api/src/modules/ControllerModule.ts

Fixes #1237
- Added `expects` in the test to explicitly show the v1 vs v2 behaviour

fix(apps/legacy-api): listswaps endpoint returning quote and base swapped

---

packages/whale-api-client/src/api/PoolPairs.ts
packages/whale-api-client/src/api/Prices.ts

Whale migration is reliant on the latest changes to `whale-api-client`. To keep this update separate from `apps/whale-api` migration we introduce these updates in a smaller PR.
Required updates for upcoming updates to PR:
- https://github.com/DeFiCh/jellyfish/pull/1168

chore(whale-api-client): update from latest whale changes

---

apps/legacy-api/src/modules/LoggingModule.ts
apps/legacy-api/src/modules/RootModule.ts

A simple LoggingInterceptor and LoggingModule to log production errors.
Partially fixes #1276, while this is a simple inclusion to log errors. Ultimately we still need to work on #1276 to refactor and implement a standardized error handling pattern.

chore(apps/legacy-api): simple LoggingInterceptor to log production errors

---

.github/workflows/ci.yml
.github/workflows/release-apps.yml
apps/nest-cli.json
apps/package.json
apps/status-api/README.md
apps/status-api/src/index.ts
apps/status-api/src/modules/ControllerModule.ts
apps/status-api/src/modules/RootModule.ts
apps/status-api/src/modules/WhaleApiModule.ts
apps/status-api/testing/StatusApiTesting.ts
apps/status-api/testing/StatusStubServer.ts

Branch out from https://github.com/DeFiCh/jellyfish/pull/1275
Part of https://github.com/DeFiCh/jellyfish/issues/1270

feat(status-api): Status API server setup

---

apps/status-api/__test__/controllers/BlockchainController.test.ts
apps/status-api/src/controllers/BlockchainController.ts
apps/status-api/src/modules/ControllerModule.ts

This includes the status api to return the status of the blockchain
operational: < 30 mins
degraded: 30-45 mins
outage: > 45 mins
Fixes https://github.com/DeFiCh/jellyfish/issues/1271

feat(status-api): Status API for Blockchain 

---

apps/playground-api/__tests__/modules/PlaygroundModule.test.ts
apps/playground-api/src/setups/setup.loan.token.ts

feat(apps/playground-api): support loan token topup in light wallet

---

packages/jellyfish-api-core/__tests__/category/loan/paybackLoan.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_loan_payback_loan.test.ts
packages/jellyfish-transaction/__tests__/script/dftx/dftx_loans/PaybackLoanV2.test.ts

Added tests for dftx paybackLoanV2 and a test for dTSLA paid by other dToken
Fixes #1295
Fixes #1296

fix(jellyfish-api-core): Fixes for jellyfish #1295 and #1296 issues

---

apps/playground-api/__tests__/modules/PlaygroundModule.test.ts
apps/playground-api/src/setups/setup.dex.ts

feat(apps/playground): add new poolpair for BTC-USDT

---

apps/legacy-api/src/controllers/PoolPairController.ts

- Fix undefined address causing account history lookup failure
- Improve logging to show last evaluated page if an error is thrown during cache warmup

fix(apps/legacy-api): undefined address causing account history lookup failure

---

apps/status-api/src/controllers/OracleStatusController.ts

To fix the cache duration to the correct value of 5 seconds
Fixes #

fix(status-api): Update cache duration correctly to 5 seconds

---

.github/scripts/release-report.js
.github/workflows/ci.yml
README.md

Fixes https://github.com/JellyfishSDK/jellyfish/issues/1370

chore(migrate): migrate codecov and ghcr.io to jellyfishsdk

---

Dockerfile

To speed up GitHub actions cycle time and concurrency since GH actions only allow 20 workflows to be run at any time.

chore(dockerfile): optimize workspace build performance

---

.github/workflows/release-apps.yml
.idea/dictionaries/fuxing.xml

https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md

chore(dockerfile): add buildcache optimization

---

.github/workflows/oss-governance-bot.yml
.github/workflows/oss-governance-labeler.yml

Add PAT for workflows to trigger other workflows.

chore(workflows): add PAT for workflow to trigger workflows

---

.github/workflows/ci.yml
apps/playground-api/__tests__/modules/PlaygroundModule.test.ts
apps/playground-api/src/setups/setup.gov.ts

chore(apps/playground-api, ci): Extend pg future swap block_period

---

apps/whale/src/module.api/_module.ts
apps/whale/src/module.api/address.controller.e2e.ts
apps/whale/src/module.api/address.controller.ts
apps/whale/src/module.api/cache/defid.cache.ts
apps/whale/src/module.api/cache/global.cache.ts
apps/whale/src/module.api/loan.collateral.controller.e2e.ts
apps/whale/src/module.api/loan.scheme.controller.e2e.ts
apps/whale/src/module.api/loan.token.controller.e2e.ts
apps/whale/src/module.api/loan.vault.controller.e2e.ts
apps/whale/src/module.api/masternode.controller.e2e.ts
apps/whale/src/module.api/masternode.service.ts
apps/whale/src/module.api/poolpair.controller.e2e.ts
apps/whale/src/module.api/poolpair.controller.ts
apps/whale/src/module.api/poolpair.prices.service.ts
apps/whale/src/module.api/poolpair.service.ts
apps/whale/src/module.api/poolswap.pathfinding.service.ts
apps/whale/src/module.api/rawtx.controller.e2e.ts
apps/whale/src/module.api/rawtx.controller.ts
apps/whale/src/module.api/rpc.controller.ts
apps/whale/src/module.api/stats.controller.ts
apps/whale/src/module.api/transaction.controller.e2e.ts
apps/whale/src/module.database/provider.level/level.database.spec.ts
apps/whale/src/module.database/provider.memory/memory.database.spec.ts
apps/whale/src/module.indexer/model/script.activity.ts
apps/whale/src/module.indexer/model/script.unspent.ts
apps/whale/src/module.indexer/model/transaction.ts
apps/whale/src/module.indexer/model/transaction.vin.ts
apps/whale/src/module.indexer/model/transaction.vout.ts

- Shortens some imports
- Synchronises `apps/whale/src` with `whale/src` (sitting in https://github.com/JellyfishSDK/whale)
Part of #977 
- Based on #1452 
- Any renaming / refactoring to Jellyfish conventions should be done in a future backwards-compatible PR
- To check that the source code is at parity with whale, can roughly follow the steps here https://github.com/JellyfishSDK/jellyfish/pull/1248#issuecomment-1076014532
- We should freeze code changes to Whale after this is merged (only allowing critical patches / fixes), then make a staging release to perform some checkouts

chore(whale-migration): whale sync

---

apps/libs/caches/__tests__/SemaphoreCache.test.ts
apps/libs/caches/src/SemaphoreCache.ts
apps/whale-api/__sanity__/WhaleSanityContainer.sanity.ts
apps/whale-api/src/module.api/actuator.e2e.ts
apps/whale-api/src/module.model/_model.probes.ts

Adds these commits:
- https://github.com/JellyfishSDK/whale/pull/975
- https://github.com/JellyfishSDK/whale/pull/973
No changes made to whale-api-client / whale-api-wallet in the interim.
Part of #977

chore(whale-api): add recent commits

---

packages/whale-api-client/package.json
packages/whale-api-wallet/package.json

Enables whale package release from jellyfish now that we have consolidated whale into this ecosystem.

feat(whale): release to npm from consolidated jellyfish

---

packages/jellyfish-api-core/__tests__/category/masternode/setGov.test.ts

Fixes #https://github.com/DeFiCh/ain/pull/1357

feat(jellyfish-api-core): Add tests for dusd burn attribute keys.
