JellyfishSDK/jellyfish

.github/CODEOWNERS

/kind chore
Collective code owner for parts of jellyfish mono repo packages. This bring in better long term maintainability of the project, and for contingency reasons too.

setup collective code owner for this mono repo

---

packages/testcontainers/src/chains/container.ts

/kind chore
Current error message is not useful for debugging, especially worst if debugging with the logs from CI.

better error message for defid-rpc-error

---

package-lock.json
packages/jellyfish-core/README.md
packages/jellyfish-core/__tests__/category/wallet.test.ts
packages/jellyfish-core/__tests__/container_adapter_client.ts
packages/jellyfish-core/__tests__/core.test.ts
packages/jellyfish-core/__tests__/json.test.ts
packages/jellyfish-core/package.json
packages/jellyfish-core/src/category/mining.ts
packages/jellyfish-core/src/category/wallet.ts
packages/jellyfish-core/src/core.ts
packages/jellyfish-core/src/json.ts
packages/testcontainers/__tests__/chains/reg_test_container.test.ts
packages/testcontainers/src/chains/reg_test_container.ts

/kind feature
> This is a JS library design balancing act, beginner friendly yet accurate.
This implements a JSON parser for `jellyfish-core` with no risk of losing precision with parse and stringify. As not all number parsed are significant in all context, (e.g. `mining.getMintingInfo()`) this allow jellyfish library users to use the `number` for non precision sensitive operation (e.g. `networkhashps`) and BigNumber for precision sensitive operations.
`JellyfishJSON` allows parsing of JSON with 'lossless', 'bignumber' and 'number' numeric precision.
* **'lossless'** uses LosslessJSON that parses numeric values as LosslessNumber. With LosslessNumber, one can perform
regular numeric operations, and it will throw an error when this would result in losing information.
* **'bignumber'** parse …

jellyfish-core with lossless, bignumber and number precision implementation

---

package-lock.json
packages/jellyfish-core/__tests__/container_adapter_client.ts
packages/jellyfish-core/__tests__/core.test.ts
packages/jellyfish-core/src/core.ts
packages/jellyfish-jsonrpc/README.md
packages/jellyfish-jsonrpc/__tests__/jsonrpc.test.ts
packages/jellyfish-jsonrpc/jest.config.js
packages/jellyfish-jsonrpc/package.json
packages/jellyfish-jsonrpc/src/jsonrpc.ts
packages/testcontainers/src/chains/container.ts

/kind feature
This PR implements the [`JSON-RPC 1.0`](https://www.jsonrpc.org/specification_v1) specification in `jellyfish-jsonrpc` for `jellyfish-core` abstraction of `JellyfishClient` & `JellyfishError`.
Implements parts of #17
Expanded on `JellyfishError` in core with `JellyfishRPCError` and `JellyfishClientError`. 
This error raising design follows many popular implementations such as the AmazonSDK, where user config problem & issues are surfaced as ClientError, while server/validation issues are categorized as another type, RPCError in this context.

implements JSON-RPC 1.0 specification

---

.github/CODEOWNERS
.github/governance.yml
.github/workflows/oss-governance-bot.yml

/kind chore
Upgraded oss-governance-bot to v2 due to workflow automation chaining permission complications. Using a unified bot token now.
https://github.com/DeFiCh/oss-governance-bot/pull/64

upgraded oss-governance-bot to v2

---

package-lock.json
packages/testcontainers/package.json

/kind chore
By moving `@types` to dev deps for `testcontainers`, this will prevent optional licenses clause from showing up for library users.

moved @types to dev for testcontainers

---

packages/jellyfish-core/package.json
packages/jellyfish-jsonrpc/package.json
packages/jellyfish/package.json
packages/testcontainers/package.json

/kind chore
So that publish flags are always included for new sub repo for consistency.

added explicit publish flags for package-json

---

.github/dependabot.yml

/kind chore
* testcontainers project was missing in `dependabot.yml`
* added wildcard to ignore all `@defichain/*` deps as they are in a monorepo updated before being published

dependabot.yml to include testcontainers and ignore local projects

---

.github/CODEOWNERS

/kind chore
In https://github.com/DeFiCh/jellyfish/pull/64 `website` is used instead of `docs` for jellyfish documentation website

renamed docs to website for CODEOWNERS

---

packages/api-core/README.md
packages/api-core/__tests__/container_adapter_client.ts
packages/api-core/__tests__/index.test.ts
packages/api-core/src/index.ts
packages/api-jsonrpc/__tests__/index.test.ts
packages/api-jsonrpc/src/index.ts
website/docs/jellyfish/design.md
website/docs/jellyfish/usage.md

/kind refactor
Removing all jellyfish keyword from `api-core`, renamed `JellyfishError` to `ApiError`.

renamed JellyfishError to ApiError

---

package-lock.json
packages/jellyfish-api-jsonrpc/package.json
packages/jellyfish-api-jsonrpc/src/index.ts

Updated `cross-fetch` to `3.1.2`, this introduces better typescript support but causes breaking change to the exported types. Requiring a manual patch.

update cross-fetch to 3.1.2

---

packages/testcontainers/src/chains/container.ts
packages/testcontainers/src/chains/reg_test_container.ts

Following the latest release of https://github.com/DeFiCh/ain/releases/tag/v1.6.0

update testcontainers to use 1.6.0

---

.github/CODEOWNERS

/kind chore
Added @canonbrother to be part of the jellyfish core code owners.

added canonbrother to CODEOWNERS

---

.idea/dictionaries/fuxing.xml
README.md
package-lock.json
packages/jellyfish-network/src/index.ts
packages/jellyfish-transaction/README.md
packages/jellyfish-transaction/__tests__/buffer/buffer_composer.test.ts
packages/jellyfish-transaction/__tests__/buffer/buffer_varuint.test.ts
packages/jellyfish-transaction/jest.config.js
packages/jellyfish-transaction/package.json
packages/jellyfish-transaction/src/buffer/buffer_composer.ts
packages/jellyfish-transaction/src/buffer/buffer_varuint.ts
packages/jellyfish-transaction/tsconfig.json
tsconfig.json
website/docs/introduction.md

/kind feature
A dead simple modern stateless raw transaction builder for DeFi.
This is the first in a series of PRs to DeFi raw transaction builder in JavaScript.
This composer design is bi-directional, allows you to `fromBuffer()` or `toBuffer()` composing. In short you compose from a byte buffer to JavaScript Object or JavaScript Object to a byte buffer. This is little endian by design as DeFi uses LE.
```ts
export class CTransaction extends ComposableBuffer<Transaction> implements Transaction {
public get version (): Version {
return this.data.version
}
public get vin (): Vin[] {
return this.data.vin
}
public get vout (): Vout[] {
return this.data.vout
}
public get lockTime (): LockTime {
return this.data.lockTime
}
composers (tx: Transaction): BufferComposer[] {
return [ …
```

jellyfish transaction buffer composer

---

.github/CODEOWNERS

/kind chore
Change in ownership priority and inclusion of @canonbrother into `jellyfish-json` due to recent work on it.

updated CODEOWNERS to include latest ownership priority and preference

---

packages/jellyfish-transaction/__tests__/index.test.ts
packages/jellyfish-transaction/__tests__/tx_composer.test.ts
packages/jellyfish-transaction/src/index.ts

/kind feature
Added constants and `export * tx/tx_composer` to jellyfish-transaction `/index.ts`

jellyfish-transaction constants and module export

---

.github/CODEOWNERS
.github/governance.yml
.github/labels.yml
.idea/dictionaries/fuxing.xml
package-lock.json
packages/jellyfish-crypto/README.md
packages/jellyfish-crypto/__tests__/elliptic.test.ts
packages/jellyfish-crypto/__tests__/hash.test.ts
packages/jellyfish-crypto/jest.config.js
packages/jellyfish-crypto/package.json
packages/jellyfish-crypto/src/bip66.d.ts
packages/jellyfish-crypto/src/der.ts
packages/jellyfish-crypto/src/elliptic.ts
packages/jellyfish-crypto/src/hash.ts
packages/jellyfish-crypto/src/index.ts
packages/jellyfish-crypto/tsconfig.json

/kind feature
Created a new package `jellyfish-crypto`. 
- `hash.ts`
- RIPEMD160
- SHA256
- HASH160
- dSHA256
- DERSignature
- encode
- decode
- EllipticPair
- SECP256K1
1. SECP256K1 is non hd, mainly for testing or non hd node design. SECP256K1 interface will not be exported, internal only.
2. EllipticPair will be used for `wallet-core` package for HDNode
3. EllipticPair must generate DER Signature and SIGHASHTYPE must not be included

jellyfish-crypto

---

packages/testcontainers/__tests__/chains/container.test.ts
packages/testcontainers/__tests__/chains/masternode.test.ts
packages/testcontainers/src/chains/container.ts
packages/testcontainers/src/chains/reg_test_container.ts

/kind feature
new testcontainers utils for better raw tx testing quality of life.
1. `container.waitForCondition(async () => false, 3000))`
2. `container.waitForWalletBalanceGTE(200)`
3. `container.fundAddress(address, 10)`
4. `const { address, privKey } = await container.newAddressAndPrivKey()`
This makes it easier to test condition that require balance, funded address, or priv key.
Also added `{ v: true }` flag so that associated docker volumes get removed after the test.

new testcontainers utils for raw tx QOL testing

---

.idea/dictionaries/fuxing.xml
packages/testcontainers/src/chains/reg_test_container.ts

/kind chore
Making testcontainers easier for testing, enabled these 2 flags.
- txindex
Maintain a full transaction index, used by the getrawtransaction rpc call
- acindex
Maintain a full account history index, tracking all accounts balances changes. Used by the listaccounthistory and accounthistorycount rpc calls
/cc @canonbrother

added acindex=1 and txindex=1 to reg_test_containers

---

packages/testcontainers/__tests__/chains/reg_test_container/index.test.ts
packages/testcontainers/__tests__/chains/reg_test_container/masternode.test.ts
packages/testcontainers/src/chains/container.ts
packages/testcontainers/src/chains/reg_test_container.ts

/kind fix
1. fundAddress implies it's funding an address for use, it should wait for confirmations
2. refactor newAddressAndPrivKey to newAddressKeys as it return both pub/priv for better testing OOL

fix fundAddress should wait confirmations

---

.gitignore
packages/jellyfish-api-core/__tests__/container_adapter_client.ts
packages/jellyfish-api-core/src/category/blockchain.ts
packages/jellyfish-api-core/src/index.ts
packages/jellyfish-api-jsonrpc/src/index.ts
packages/jellyfish-json/__tests__/index.test.ts
packages/jellyfish-json/__tests__/remap.test.ts
packages/jellyfish-json/src/index.ts
packages/jellyfish-json/src/remap.ts
website/docs/jellyfish/design.md

/kind fix
A balancing act between BigNumber parsing and effective usage. I redesigned it to use path based mapping. It will map all within a path to the specific precision. This allow flexibility json parsing and an easy to use interface. 
For the bellow setup, only `h` and `d.f.f1` will be number, while the request get remapped to `BigNumber`.
```ts
const losslessObj = parse(`
{
"a": 1.2,
"b": [1.2, 1.2],
"c": { "c1": 1.2, "c2": [1.2] },
"d": {
"e": {
"e1": 1.2,
"e2": [1.2, 1.2],
"e3": { "e3a": 1.2, "e3b": [1.2] }
},
"f": {
"g": 1.2,
"f1": 1.2
}
},
"h": 1.2
}
`)
const remapped = remap(losslessObj, {
a: 'bignumber',
b: 'bignumber',
c: 'bignumber',
d: {
e: 'bignumber',
f: {
g: 'bignumber'
}
}
})
```
I also changed JSON-RPC 1.0 to handle precision on result only.
Fixes #104

fix jellyfish-json path based bignumber remapping

---

package-lock.json
packages/jellyfish-crypto/__tests__/bech32.test.ts
packages/jellyfish-crypto/__tests__/elliptic.test.ts
packages/jellyfish-crypto/__tests__/wif.test.ts
packages/jellyfish-crypto/package.json
packages/jellyfish-crypto/src/bech32.ts
packages/jellyfish-crypto/src/elliptic.ts
packages/jellyfish-crypto/src/index.ts
packages/jellyfish-crypto/src/wif.ts

/kind feature
Added WIF to jellyfish-crypto since it can be used to get a private key using secp256k1.
Added bech32 address `from` and `to` utils to jellyfish-crypto as it uses HASH160 function to encode addresses.

added bech32 & wif into jellyfish-crypto

---

package.json
packages/jellyfish-api-core/package.json
packages/jellyfish-api-jsonrpc/package.json
packages/jellyfish-crypto/package.json
packages/jellyfish-json/package.json
packages/jellyfish-network/package.json
packages/jellyfish-transaction/package.json
packages/jellyfish-wallet-mnemonic/package.json
packages/jellyfish-wallet-whale/package.json
packages/jellyfish-wallet/package.json
packages/testcontainers/package.json
packages/testcontainers/tsconfig.json

/kind refactor
removed devDependencies.typescript from sub-packages as it's only required at the package root.

removed devDependencies.typescript from sub-packages

---

packages/jellyfish-transaction/__tests__/buffer/buffer_composer.test.ts
packages/jellyfish-transaction/src/buffer/buffer_bignumber.ts
packages/jellyfish-transaction/src/buffer/buffer_composer.ts
packages/jellyfish-transaction/src/buffer/buffer_varuint.ts
packages/jellyfish-transaction/src/tx_signature.ts

/kind fix
BigInt causes platform compatibility issues and it's difficult to polyfill/ponyfill. This PR moved all bigint implementation to use BigNumber.
Fixes #152

removed bigint to only use bignumber

---

packages/testcontainers/src/chains/container.ts

Bump `defi/defichain` docker image from `1.6.0` to `1.6.3`.

bump docker to defi/defichain:1.6.3

---

.idea/dictionaries/fuxing.xml
packages/jellyfish-transaction/__testcontainers__/craft_sign_send_tx.test.ts
packages/jellyfish-transaction/jest.config.js
packages/jellyfish-transaction/package.json

/kind chore
Implement part of #150 as `jellyfish-transaction` tests should be run against `testcontainers` for extra compatibility

additional test to craft_sign_send_tx using your own private key

---

packages/jellyfish-crypto/__tests__/bech32.test.ts
packages/jellyfish-crypto/__tests__/index.test.ts
packages/jellyfish-crypto/src/bech32.ts
packages/jellyfish-transaction/__tests__/tx/p2wpkh_1_to_1.test.ts
packages/jellyfish-transaction/__tests__/tx/p2wpkh_1_to_2.test.ts

/kind fix
fix Bech32.fromPubKey as it should use HASH160 not SHA256
also added Bech32.fromHash160

fix bech32 as it should use HASH160 not SHA256

---

packages/testcontainers/README.md
packages/testcontainers/src/chains/container.ts
packages/testcontainers/src/chains/reg_test_container/masternode.ts

/kind fix
wait for wallet coinbase maturity should use getBlockCount instead as it checks block count instead of generating 100 blocks. As blocks would start generating when container start, getBlockCount would reflect the actual coinbase status.

fix wait for wallet coinbase maturity should use getBlockCount

---

packages/testcontainers/src/chains/container.ts

/kind chore
Due to race conditions tryPullImage test coverage is flaky, should not add tests to get this coverage as it's will causes race conditions conflicting errors.

ignored test coverage for tryPullImage due to race conditions

---

packages/jellyfish-api-core/__tests__/category/rawtx.test.ts

/kind fix
1. `30440220`
1. `30430220`
DER signature length should not be compared in the test as it's a variable number.

fix test as signature length should not be compared

---

.idea/dictionaries/fuxing.xml
packages/jellyfish-transaction/__tests__/tx_signature/sign_input.test.ts
packages/jellyfish-transaction/__tests__/tx_signature/sign_transaction.test.ts
packages/jellyfish-transaction/src/tx_signature.ts
packages/jellyfish-wallet-mnemonic/__tests__/mnemonic/bip32.test.ts
packages/jellyfish-wallet/__tests__/wallet_hd_node.test.ts

/kind feature
Attempting to sign a txn without any vout will fail.
Attempting to sign a txn input P2WPKH will fail if provided prevout and elliptic pair are mismatched.
Fixes #134

txn input validation (length, mismatch prevout)

---

package-lock.json
packages/testing/package.json

/kind fix
moved from peer dependencies to just dependencies instead as Lerna automatically update the dependencies and it will conflict with peer resolution.

removed peer deps for internal deps

---

packages/testcontainers/src/chains/reg_test_container/masternode.ts

/kind refactor
`MasterNodeRegTestContainer.generate` make 2 additional RPC per generate to get block hash however, those block hash are never used in any context. Hence it's redundant, removing to speed up tests.

removed 2 redundant RPC that are never used in container.generate

---

packages/jellyfish-transaction/__testcontainers__/craft_sign_send_tx.test.ts
packages/jellyfish-transaction/__tests__/index.test.ts
packages/jellyfish-transaction/__tests__/tx/p2wpkh_1_to_1.test.ts
packages/jellyfish-transaction/__tests__/tx/p2wpkh_1_to_2.test.ts
packages/jellyfish-transaction/__tests__/tx_composer/CTransaction.test.ts
packages/jellyfish-transaction/__tests__/tx_composer/CTransactionSegWit.test.ts
packages/jellyfish-transaction/__tests__/tx_composer/CTransactionV2.test.ts
packages/jellyfish-transaction/__tests__/tx_composer/CVout.test.ts
packages/jellyfish-transaction/__tests__/tx_signature/sign_input.test.ts
packages/jellyfish-transaction/__tests__/tx_signature/sign_transaction.test.ts
packages/jellyfish-transaction/src/tx.ts
packages/jellyfish-transaction/src/tx_composer.ts
packages/jellyfish-transaction/src/tx_signature.ts
packages/jellyfish-wallet-mnemonic/__tests__/mnemonic/bip32.test.ts

/kind refactor
`dct_id` naming convention is inconsistent with other variable and project across the field. Hence renaming to `tokenId` for consistency

renamed dct_id to tokenId to keep naming convention consistent

---

packages/jellyfish-api-core/__tests__/category/rawtx.test.ts
packages/testing/__tests__/rawtx.test.ts

/kind chore
Currently, RawTxn tests are checking DER signature length, it should not.

fixed `rawtx.test.ts` to be deterministic

---

packages/jellyfish-api-core/__tests__/category/blockchain.test.ts
packages/jellyfish-api-core/src/category/blockchain.ts
website/docs/jellyfish/api/blockchain.md

/kind feature
Add getChainTips rpc

Add getChainTips rpc

---

packages/testcontainers/__tests__/index.test.ts
packages/testcontainers/src/chains/container.ts
packages/testcontainers/src/chains/main_net_container.ts
packages/testcontainers/src/chains/reg_test_container/index.ts
packages/testcontainers/src/chains/reg_test_container/masternode.ts
packages/testcontainers/src/chains/test_net_container.ts

/kind feat
With this, you can override testcontainers default docker image to test bleeding-edge features.

added ability to override testcontainers docker image

---

packages/jellyfish-api-core/__tests__/category/mining.test.ts
packages/jellyfish-api-core/src/category/mining.ts
website/docs/jellyfish/api/mining.md

/kind feature
`getMintingInfo` is deprecated since adding multiple masternode support from within one server:
https://github.com/DeFiCh/ain/blob/df796cb7d6dbbe0ed7d051e79db0f36630f77afb/src/rpc/mining.cpp#L220
This PR adds `getMiningInfo` which is the implementation to support multiple mining masternodes:
https://github.com/DeFiCh/ain/blob/df796cb7d6dbbe0ed7d051e79db0f36630f77afb/src/rpc/mining.cpp#L276
* Added docs with a deprecated comment for the old one, but please advise if this is the correct way
* `getMintingInfo` is used as an example in some places, let me know if this PR should replace the examples as well
* Let me know if the test data should include a second node now, since there's an array to test now

Add new getMiningInfo for multiple masternode support

---

package-lock.json
packages/jellyfish-crypto/__tests__/bech32.test.ts
packages/jellyfish-crypto/__tests__/bs58.test.ts
packages/jellyfish-crypto/package.json
packages/jellyfish-crypto/src/bech32.ts
packages/jellyfish-crypto/src/bs58.ts
packages/jellyfish-crypto/src/index.ts

/kind feature
- utility for other package to encode/decode b58
- more generic, should for other network B58 address after ICX too
Fixes #

add bs58 to jellyfish-crypto

---

packages/testing/__tests__/token.test.ts
packages/testing/src/token.ts

/kind feature
Testing module `token.createToken` to return `number` id of the created token for testing QOL.

`@defichain/testing` createToken to return id number

---

packages/jellyfish-wallet-mnemonic/__tests__/mnemonic/bip32.test.ts

/kind fix
As the signature is an integer if the integer is lesser than the 'encoded 70' it can be lesser. Probability is low but it's there.

fixed bip32.test.ts flakiness test as signature length can be lesser than 70

---

packages/jellyfish-network/src/index.ts

/kind refactor
`jellyfish-network` `interface Network` to use exact variable instead primitive for type safety.

network interface to use exact variable instead primitive

---

packages/jellyfish-address/__tests__/base58_address.test.ts
packages/jellyfish-address/__tests__/bech32_address.test.ts
packages/jellyfish-address/__tests__/p2pkh.test.ts
packages/jellyfish-address/__tests__/p2sh.test.ts
packages/jellyfish-address/__tests__/p2wpkh.test.ts
packages/jellyfish-address/__tests__/p2wsh.test.ts
packages/jellyfish-address/src/index.ts

/kind refactor
Avoid ES6 default export at all cost, technical debt minter.

refactor DeFiAddress to export const

---

packages/jellyfish-transaction-builder/__tests__/provider.mock.ts
packages/jellyfish-transaction-builder/__tests__/raw_crafting.ts
packages/jellyfish-transaction/__tests__/buffer/buffer_composer.test.ts
packages/jellyfish-transaction/__tests__/index.test.ts
packages/jellyfish-transaction/__tests__/tx_composer/CTransaction.test.ts
packages/jellyfish-transaction/__tests__/tx_composer/CTransactionSegWit.test.ts
packages/jellyfish-transaction/__tests__/tx_composer/CVin.test.ts
packages/jellyfish-transaction/__tests__/tx_signature/sign_input.test.ts
packages/jellyfish-transaction/src/buffer/buffer_composer.ts
packages/jellyfish-transaction/src/script/mapping.ts
packages/jellyfish-transaction/src/tx_composer.ts
packages/jellyfish-transaction/src/tx_segwit.ts
packages/jellyfish-transaction/src/tx_signature.ts
packages/jellyfish-wallet-mnemonic/__tests__/mnemonic/bip32.test.ts

/kind chore
`Vin.txid` to be decoded in BE order but re-encoded as LE. This is for consistency with defid, see #231 
Fixes #231

Vin.txid to be decoded in BE order

---

packages/jellyfish-api-core/__tests__/container_adapter_client.ts
packages/jellyfish-api-core/src/index.ts
packages/jellyfish-api-jsonrpc/__tests__/index.test.ts
packages/jellyfish-api-jsonrpc/src/index.ts

/kind fix
1. RpcApiError passed in wrong param
2. rename `rpcMethod` to just `method`, `Rpc` is already part of the class name.
3. Added stricter test to assert errors.

fix RpcApiError rpcMethod wrong param

---

packages/jellyfish-api-core/__tests__/category/wallet.test.ts
packages/jellyfish-api-core/src/category/wallet.ts
website/docs/jellyfish/api/wallet.md

Add `wallet.sendMany` RPC

---

.github/workflows/ci.yml
package.json

/kind chore
- Improved CI performance for running test by adding -maxWorkers=4 (CI uses 2 core, 2x2 = 4).
- Added caching for NPM for better CI performance
TLDR, reduce the longest workflow from 20++ minutes to under 10 minutes.

Faster CI with --maxWorkers=4 + npm caching

---

.idea/dictionaries/fuxing.xml
packages/jellyfish-api-core/__tests__/category/wallet.test.ts

/kind refactor
`jellyfish-api-core` must not share the same container for different RPC. It’s getting very difficult to maintain side-effect and writing independent tests.

Refactor createWallet test to be independent 

---

packages/jellyfish-api-core/__tests__/category/account.test.ts
packages/jellyfish-api-core/__tests__/category/account/accountToAccount.test.ts
packages/jellyfish-api-core/src/category/account.ts
website/docs/jellyfish/api/account.md

/kind feature
Add accounttoaccount rpc and assertion to prevent sending DFI in account form
Fixes #228

Add `accountToAccount` RPC

---

packages/testcontainers/src/chains/defid_container.ts
packages/testcontainers/src/chains/reg_test_container/index.ts

Added ability to specify image as an env var
/kind chore
Update defid_container.ts to be able to use env var to specify image tag
Fixes #

Able to specify image tag via ENV in `defid_container.ts`

---

jest.config.js
package.json
packages/jellyfish-wallet-mnemonic/__tests__/mnemonic/bip32.test.ts
packages/jellyfish-wallet/src/wallet_account.ts
packages/testing/src/poolpair.ts
tsconfig.base.json
tsconfig.build.json
tsconfig.json

fix mono repo ts config

---

.github/workflows/oss-governance-project-pr.yml

/kind chore
If there a merge conflict, it will fail. Running on target won't.

fix oss-governance-project-pr to only run on pr target

---

package-lock.json
packages/jellyfish-crypto/__tests__/aes256.test.ts
packages/jellyfish-crypto/package.json
packages/jellyfish-crypto/src/aes256.ts
packages/jellyfish-crypto/src/browserify-aes.d.ts
packages/jellyfish-crypto/src/index.ts

/kind feature
Dependency of #133 .
Existing lib in found in npm has no TS @types support, so build a simple one directly from `crypto`.
Simplified implementation, all arg and return are buffer only.
Fixes #

`jellyfish-crypto`: aes256

---

README.md
packages/jellyfish-api-core/README.md
website/docs/jellyfish/design.md
website/docs/jellyfish/usage.md

/kind feature
Changed various `.md` files that uses `getMintingInfo()` in code examples.
Fixes #230 
This PR does not change the docs in `testcontainers` as the containers do not have `getMiningInfo()` as a shorthand method like they have with `getMintingInfo()`. An issue has been created to address this. #376

Fixed doc files from getMintingInfo to getMiningInfo

---

packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_account_utxos_to_account.test.ts
packages/jellyfish-transaction-builder/src/txn/txn_builder_account.ts

/kind feature
Allow split output tokens into multiple address (as DeFiChain supported)
Fixes #270

`jellyfish-transaction-builder`: utxos-to-account support multiple destination addresses

---

tsconfig.base.json

/kind chore
Removed noUnusedLocals from `tsconfig.base.json` too strict during dev making it hard to do dirty testing, by default lint will catch it during PR.

removed noUnusedLocals from tsconfig.base.json too strict during dev

---

.github/CODEOWNERS

/kind chore
Reduce `CODEOWNERS` responsibilities for ICX and Oracle. Added @ivan-zynesis to ICX for future `jellyfish-transaction` context.
To allow better code ownership experience for https://github.com/DeFiCh/jellyfish/pull/357

updated icx and oracle codeowners responsibility

---

packages/jellyfish-crypto/__tests__/elliptic.test.ts

/kind chore
Flaky test coverage due to nondeterministic code, added should sign hash Buffer with signature buffer [0] as 0x80 to fix coverage.

should sign hash Buffer with signature buffer [0] as 0x80 for coverage

---

packages/jellyfish-api-core/__tests__/category/wallet/getUnconfirmedBalance.test.ts
packages/jellyfish-api-core/src/category/wallet.ts
website/docs/jellyfish/api/wallet.md

/kind feature
Added getUnconfirmedBalance RPC
1. wallet.getUnconfirmedBalance
Fixes `getunconfirmedbalance` #48 
Did not test for `getUnconfirmedBalance(true)` because it is not tested or used any where in any app.
Did not test for `untrusted_pending` because requires multi-node set up.

Added `wallet.getUnconfirmedBalance` RPC

---

packages/jellyfish-api-core/src/category/poolpair.ts
website/docs/jellyfish/api/poolpair.md

/kind fix
Update the status type of poolpair customRewards which is nullable
Fixes #393
Ref:
https://github.com/DeFiCh/ain/blob/7a430185fd3029e9ee8974fde4e65c715fb9db04/src/masternodes/rpc_poolpair.cpp#L51-L59

poolpair.customRewards is nullable

---

README.md
package-lock.json
packages/jellyfish-address/tsconfig.build.json
packages/jellyfish-api-core/package.json
packages/jellyfish-api-core/tsconfig.build.json
packages/jellyfish-api-jsonrpc/package.json
packages/jellyfish-api-jsonrpc/tsconfig.build.json
packages/jellyfish-json/package.json
packages/jellyfish-transaction-builder/package.json
packages/jellyfish-transaction-builder/tsconfig.build.json
packages/jellyfish-transaction-signature/tsconfig.build.json
packages/jellyfish-wallet-mnemonic/tsconfig.build.json
packages/jellyfish-wallet/tsconfig.build.json
packages/jellyfish/package.json
packages/jellyfish/tsconfig.json
packages/testing/tsconfig.build.json

/kind refactor
- Removed internal `devDependencies` as it can be resolved via module mapper in jest, hence not required anymore for testing.
- Removed individual project references to just use a global reference table, easier to maintain.
- Moved `@types/lossless-json` to be part of `dependencies` in `jellyfish-json`
- Fixed invalid `@defichain/jellyfish` tsconfig.json extend reference that didn't exist

removed project references and internal dev deps

---

packages/jellyfish-wallet-mnemonic/package.json
packages/jellyfish-wallet/__tests__/wallet_account.test.ts
packages/jellyfish-wallet/package.json
packages/jellyfish-wallet/src/wallet_account.ts

/kind feature
Implements `WalletHdNode` on `WalletAccount` to use the `EllipticPair` interface on the `WalletAccount` without exposing WalletHdNode directly for ease of use.

implements WalletHdNode on WalletAccount

---

packages/jellyfish-transaction/__tests__/buffer/buffer_composer.test.ts
packages/jellyfish-transaction/__tests__/tx_composer/CTransaction.test.ts
packages/jellyfish-transaction/__tests__/tx_composer/CTransactionSegWit.test.ts
packages/jellyfish-transaction/__tests__/tx_composer/index.ts
packages/jellyfish-transaction/package.json
packages/jellyfish-transaction/src/buffer/buffer_composer.ts
packages/jellyfish-transaction/src/tx_composer.ts

/kind feature
- added `toHex` in `BufferComposer`, making it easier to get transaction hex for broadcasting without importing SmartBuffer
- added `txId` for `CTransaction` & `CTransactionSegWit`, fixes #303
- added `jellyfish-crypto` into `jellyfish-transaction`

improved `jellyfish-transaction` buffer interoperability and ease of use

---

packages/jellyfish-api-core/__tests__/category/oracle/removeOracle.test.ts
packages/jellyfish-api-core/__tests__/category/oracle/setOracleData.test.ts
packages/jellyfish-api-core/__tests__/category/oracle/updateOracle.test.ts
packages/jellyfish-api-core/src/category/oracle.ts
website/docs/jellyfish/api/oracle.md

/kind fix
```ts
const utxos = await container.call('listunspent', [1, 9999999, [address], true])
```
When `utxos.length === 0`, it will pick a foundation auth, as you pass in an empty UTXO. And since addresses are new without having a UTXO, it will succeed silently. This is not the expected case. UTXO test must use `fundAddress` for consistent test behavior.
~~Also renamed `oracleid` to `oracleId` for the parameter to keep camelCase consistency for params. `oracleid` is still used for data objects since ain uses that but we should use `oracleId` on params.~~

Fixed bad test in oracle RPC and cleaned up docs for consistency

---

packages/jellyfish-transaction-signature/src/tx_signature.ts

/kind fix
Remove typecheck for OP_PUSHDATA. This fixes an issue where the typecheck denies signing a private key due to the instance type of OP_PUSHDATA not being correctly interpreted.
See: https://github.com/DeFiCh/salmon/pull/60#issuecomment-874717109
Fixes #

Remove typecheck for OP_PUSHDATA

---

packages/jellyfish-wallet/__tests__/wallet_account.test.ts
packages/jellyfish-wallet/src/wallet_account.ts

/kind fix
For many implementations it's useful to know what network the wallet function belongs to. Can refactor into a getter function if needed.
Fixes #

Allow access to network from WalletAccount

---

.github/workflows/ci.yml

/kind chore
As bash uploader `v1` is deprecated, it's using verified `v2` now

Replace `npx run codecov` with GH Actions `codecov/codecov-action`

---

packages/jellyfish-transaction-builder/__tests__/raw_crafting.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_error.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_p2wpkh.test.ts
packages/jellyfish-transaction-builder/src/txn/txn_builder.ts
packages/jellyfish-transaction-signature/__tests__/tx/p2wpkh_1_to_1.test.ts
packages/jellyfish-transaction-signature/__tests__/tx/p2wpkh_1_to_2.test.ts
packages/jellyfish-transaction-signature/__tests__/tx_signature/sign_input.test.ts
packages/jellyfish-transaction-signature/__tests__/tx_signature/sign_transaction.test.ts
packages/jellyfish-transaction-signature/src/tx_signature.ts
packages/jellyfish-wallet-classic/src/classic.ts
packages/jellyfish-wallet-mnemonic/src/mnemonic.ts
packages/jellyfish-wallet/__tests__/node.mock.ts

/kind fix
SignInputOption should not require EllipticPair to prevent the wrong use of the EllipticPair interface. E.g. accessing privKey.
Also added `TransactionSigner.signPrevoutsWithEllipticPairs` to keep EllipticPair implementation dry.

SignInputOption should not require EllipticPair

---

README.md
packages/jellyfish-address/README.md
packages/jellyfish-api-core/README.md
packages/jellyfish-api-jsonrpc/README.md
packages/jellyfish-crypto/README.md
packages/jellyfish-json/README.md
packages/jellyfish-network/README.md
packages/jellyfish-transaction-builder/README.md
packages/jellyfish-transaction-signature/README.md
packages/jellyfish-transaction/README.md
packages/jellyfish-wallet-classic/README.md
packages/jellyfish-wallet-encrypted/README.md
packages/jellyfish-wallet-mnemonic/README.md
packages/jellyfish-wallet/README.md
packages/jellyfish/README.md
packages/testcontainers/README.md
packages/testing/README.md
website/docs/introduction.md

/kind docs
All release are released into `npm@latest` by default now, hence deprecating the `npm@next` badge.

removed npm@next badge

---

packages/jellyfish-api-core/__tests__/category/oracle/appointOracle.test.ts
packages/jellyfish-api-core/__tests__/category/oracle/updateOracle.test.ts

/kind feature
These 2 Oracle rpcs should allow weightage value from 0 to 255,  not 1 to 100.
Fixes #509

AppointOracle and UpdateOracle rpcs should allow weightage value from 0 to 255

---

packages/jellyfish-api-core/__tests__/category/icxorderbook/listHTLCs.test.ts
packages/jellyfish-api-core/__tests__/category/mining/getMiningInfo.test.ts
packages/testcontainers/__tests__/chains/container.test.ts
packages/testcontainers/__tests__/chains/container_restart.test.ts
packages/testcontainers/__tests__/containerRestart.test.ts
packages/testcontainers/src/chains/defid_container.ts
packages/testcontainers/src/chains/docker_container.ts
packages/testcontainers/src/chains/reg_test_container/masternode.ts

/kind fix
restart functionality to MasterNodeRegTestContainer. This allows to restart containers in the middle of the test with additional defid options. This allows fixing the problem with generating blocks to newly created masternodes.
Fixes #
depends https://github.com/DeFiCh/ain/pull/646

Added `restart` to MNRegContainer to fix `generatetoaddress`

---

packages/jellyfish-transaction/__tests__/script/dftx/dftx_op_push_anomaly.test.ts
packages/jellyfish-transaction/src/script/dftx/index.ts

/kind fix
Fixed `dftx` to parse anomalous `OP_PUSHDATA`. 
e.g: `[OP_RETURN, OP_PUSH_DATA, OP_PUSH_DATA]`

fixed dftx to parse anomalous OP_PUSHDATA

---

packages/jellyfish-transaction/__tests__/script/dftx/dftx_pool/PoolSwap.test.ts
packages/jellyfish-transaction/src/buffer/buffer_composer.ts

/kind fix
Because maxPrice consistency structure is not enforced at the transaction level, `jellyfish-transaction` must be able to parse without erroring out. This PR will convert inconsistent maxPrice representation into the consistent variant.

inconsistent `maxPrice` should parse from buffer into consistent variant regardless

---

package-lock.json
packages/jellyfish-wallet-encrypted/__tests__/bip32.test.ts
packages/jellyfish-wallet-mnemonic/__tests__/bip32.test.ts
packages/jellyfish-wallet-mnemonic/package.json
packages/jellyfish-wallet-mnemonic/src/hd_node.ts
packages/jellyfish-wallet/__tests__/wallet.test.ts
packages/jellyfish-wallet/src/wallet.ts

/kind feature
`@defichain/jellyfish-wallet-mnemonic` to use a unique seed of `"@defichain/jellyfish-wallet-mnemonic"` different from the default of `"Bitcoin seed"`.
- This will ultimately lock our implementation to be only usable with our library. This means the `24 phrases` will only work with the jellyfish libraries. This prevents users from attempting to export/import phrases from other libraries and creating a compatibility nightmare for us due to incompatible derivation techniques. We could intervene in UX but better if done and dealt with at the implementation core.
- With our own unique seed, a stolen 24 phrase will not be as easy to crack since the stealer will need to know what type of wallet this mnemonic phrase belongs to. (Not the main purpose of this refactor) …

`@defichain/jellyfish-wallet` derivation refactoring

---

.github/CODEOWNERS
packages/testcontainers/src/chains/defid_container.ts

/kind chore
To allow more concurrent connections for testing.

increase `-rpcworkqueue` to 512 for testcontainers

---

packages/jellyfish-api-core/__tests__/category/governance/getProposal.test.ts
packages/jellyfish-api-core/__tests__/category/governance/listProposals.test.ts
packages/jellyfish-api-core/src/category/governance.ts
website/docs/jellyfish/api/governance.md

/kind fix
Type BigNumber instead of number in interface ProposalInfo amount property

Use BigNumber for Governance ProposalInfo amount property

---

packages/jellyfish-wallet-mnemonic/__tests__/bip39.test.ts
packages/jellyfish-wallet-mnemonic/src/mnemonic.ts

/kind feature
Add mnemonicAsEntropy and entropyAsMnemonic for storing mnemonic as 32-byte buffer.
For `DeFiCh/wallet` to store mnemonic as 32-byte entropy without any even/odd hacks.

add mnemonicAsEntropy and entropyAsMnemonic for storing mnemonic as 32 byte buffer

---

.eslintrc
.github/workflows/ci.yml
.idea/dictionaries/fuxing.xml
package-lock.json
package.json
packages/jellyfish-api-core/__tests__/category/poolpair/poolSwapMaxPrice.test.ts
packages/jellyfish-api-core/__tests__/category/spv/decodeHtlcScript.test.ts
packages/jellyfish-api-core/__tests__/category/wallet/sendMany.test.ts
packages/jellyfish-api-core/__tests__/category/wallet/wallet.test.ts
packages/jellyfish-crypto/__tests__/aes256.test.ts
packages/jellyfish-json/src/index.ts
packages/jellyfish-transaction/__tests__/buffer/buffer_composer.test.ts
packages/jellyfish-transaction/src/script/dftx/dftx.ts
packages/jellyfish-transaction/src/script/dftx/dftx_account.ts
packages/jellyfish-transaction/src/script/dftx/dftx_balance.ts
packages/jellyfish-transaction/src/script/dftx/dftx_governance.ts
packages/jellyfish-transaction/src/script/dftx/dftx_masternode.ts
packages/jellyfish-transaction/src/script/dftx/dftx_misc.ts
packages/jellyfish-transaction/src/script/dftx/dftx_oracles.ts
packages/jellyfish-transaction/src/script/dftx/dftx_pool.ts
packages/jellyfish-transaction/src/script/dftx/dftx_price.ts
packages/jellyfish-transaction/src/script/dftx/dftx_token.ts
packages/jellyfish-transaction/src/script/dftx/dftx_unmapped.ts
packages/jellyfish-transaction/src/tx_composer.ts
packages/jellyfish-transaction/src/tx_segwit.ts
packages/jellyfish/src/index.ts
packages/testcontainers/src/chains/defid_container.ts
packages/testcontainers/src/wait_for_condition.ts

/kind refactor
Instead of running ts-standard, we run eslint configured to use ts-standard to allow better IDE and GitHub integration.

lint to run eslint directly instead of through standard

---

packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_account_account_to_account.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_account_account_to_utxos.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_account_utxos_to_account.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_appoint_oracle.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_claim_dfc_htlc.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_create_loan_scheme.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_dex_poolswap.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_error.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_governance_createcfp.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_governance_createvoc.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_governance_vote.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_icx_create_order.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_icx_make_offer.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_liq_pool_add_liquidity.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_liq_pool_remove_liquidity.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_masternode_create.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_masternode_resign.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_p2wpkh.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_remove_oracle.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_set_default_loan_scheme.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_set_oracle_data.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_submit_dfc_htlc.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_submit_ext_htlc.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_update_oracle.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_utxo.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_utxo_many.test.ts
packages/jellyfish-transaction-builder/src/index.ts
packages/jellyfish-transaction-builder/src/txn/txn_builder.ts
packages/jellyfish-transaction-builder/src/txn/txn_builder_governance.ts
packages/jellyfish-transaction-builder/src/txn/txn_builder_masternode.ts

/kind feature
Added additional `network: Network` param to all P2WPKHTxnBuilder, allowing `TxnBuilder` to access network information required for building transactions.

Added additional `network: Network` param to all P2WPKHTxnBuilder

---

packages/jellyfish-api-core/__tests__/category/governance/createCfp.test.ts
packages/jellyfish-api-core/__tests__/category/governance/createVoc.test.ts
packages/jellyfish-api-core/__tests__/category/governance/governance_container.ts
packages/jellyfish-api-core/__tests__/category/governance/vote.test.ts
packages/jellyfish-transaction/__tests__/script/dftx/dftx_governance/CreateCfp.test.ts
packages/jellyfish-transaction/__tests__/script/dftx/dftx_governance/Vote.test.ts
packages/jellyfish-transaction/src/script/dftx/dftx_governance.ts

/kind chore
Bumps docker image to latest governance PR state e1503fc38df50e5ca8ae4caf400d533704be12ee
Update governance opcodes to match change. 
The opcodes were changed as they were conflicting with loan opcodes.

Update governance opcodes

---

packages/jellyfish-wallet/__tests__/wallet.test.ts
packages/jellyfish-wallet/src/wallet.ts

/kind feature
Updated JellyfishWallet to use path "coinType/purpose/0/account" non-hardened derivation with:
- `coinType` support  for BTC/DFI for ICX
- `purpose` support for LIGHT_WALLET and MASTERNODE locked UTXO.
- `account` for addresses within the purpose use case. E.g. light wallet addresses, masternodes.
This won't break compatibility with DeFiCh/wallet because currently we only use one default address.
Where account = `0`.
Before:
- `1129/account/0/0 -> 1129/0/0/0`
After:
- COIN_TYPE = 1129, default
- PURPOSE = 0, default
- `coinType/purpose/0/account -> 1129/0/0/0`

jellyfish-wallet to use `coinType/purpose/0/account` pathing

---

.codeclimate.yml
.eslintrc
.github/CODEOWNERS
.github/workflows/release-drafter.yml
.gitignore
.idea/dictionaries/fuxing.xml
CONTRIBUTING.md
README.md

/kind chore
The initial start of #580 - We are consolidating all jellyfish ecosystem projects ocean, whale, playground, and salmon into this repository.
- For better synergy of DeFiChain open source development across all concerns.
- Consistent versioning for all ecosystem releases with a single source of truth.
- Documentation for the entirety of the jellyfish ecosystem via `jellyfish.defichain.com`. Incorporating sample and playground.
- Early regression detection upstream to downstream changes with monolithic repo structure.

initial jellyfish ecosystem consolidation PR setup

---

.idea/dictionaries/fuxing.xml
jest.config.js
package.json
packages/jellyfish-api-core/__tests__/category/misc/setMockTime.test.ts
packages/jellyfish-api-core/__tests__/category/poolpair/poolswap.test.ts
packages/jellyfish-api-core/__tests__/category/poolpair/testpoolswap.test.ts
packages/jellyfish-api-core/__tests__/category/rawtx/getRawTransaction.test.ts
packages/jellyfish-api-core/__tests__/category/spv/listAnchors.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_claim_dfc_htlc.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_submit_dfc_htlc.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_submit_ext_htlc.test.ts
packages/jellyfish-wallet-encrypted/tsconfig.build.json
tsconfig.json
website/docs/introduction.md

/kind chore
- fixed lint-staged with eslint config, it was running on all files instead of staged.
- removed references in each package, it's not required anymore
- remove `@defichain/jellyfish-*/*` imports within the mono repo, only index.ts should be exposed and used those are our public API while dist are internal API

remove `/*` tsconfig references 

---

.github/CODEOWNERS
.github/governance.yml
.github/labeler.yml
.github/labels.yml
.gitignore
.idea/dictionaries/fuxing.xml
examples/ocean-dex-api/.gitignore
examples/ocean-dex-api/README.md
examples/ocean-dex-api/package.json
examples/ocean-dex-api/pages/index.jsx
examples/ocean-masternodes-api/.gitignore
examples/ocean-masternodes-api/README.md
examples/ocean-masternodes-api/package.json
examples/ocean-masternodes-api/pages/index.jsx

/kind chore
Added 2 sample projects in `/examples`:
1. `/ocean-dex-api` - Ocean DEX API - This is a very simple example to fetch live DEX Pool Pair information from ocean.defichain.com.
1. `/ocean-masternodes-api` - DeFiChain Masternode - A very simple example to fetch Masternode information from ocean.defichain.com with pagination.
These 2 are the first of many example projects that will be added to `DeFiCh/jellyfish`. As part of the consolidation effort https://github.com/DeFiCh/jellyfish/issues/580, this is a great place to put all and everything related to the jellyfish ecosystem. Be it an example project or general API/SDK documentation. 
We will be adding more projects of different use cases and calibrate over the coming weeks.

added 2 sample project in `/examples`

---

packages/jellyfish-api-core/__tests__/category/loan/getCollateralToken.test.ts
packages/jellyfish-api-core/__tests__/category/loan/listCollateralTokens.test.ts
packages/jellyfish-api-core/__tests__/category/loan/listLoanTokens.test.ts
packages/jellyfish-api-core/__tests__/category/loan/loan_container.ts
packages/jellyfish-api-core/__tests__/category/loan/setCollateralToken.test.ts
packages/jellyfish-api-core/__tests__/category/loan/setLoanToken.test.ts
packages/jellyfish-buffer/src/composer.ts
packages/jellyfish-transaction-builder/__tests__/txn/loan_container.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_loan_set_collateral_token.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_loan_set_loan_token.test.ts
packages/jellyfish-transaction/__tests__/script/dftx/dftx_loans/SetCollateralToken.test.ts
packages/jellyfish-transaction/__tests__/script/dftx/dftx_loans/SetLoanToken.test.ts
packages/jellyfish-transaction/src/script/dftx/dftx_loans.ts

The latest code in the epic/loan branch (See DeFiCh/ain#742) breaks the existing code in the main branch.
The priceFeedId value is no longer an oracle TXID. It is a string with token/currency format.
/kind fix
Fixes #669

Changes priceFeedId value from oracle txid to token/currency pair

---

CONTRIBUTING.md
README.md
packages/jellyfish/README.md
packages/jellyfish/src/index.ts
packages/jellyfish/src/provider.ts

/kind chore
`@defichain/jellyfish` has been deprecated, this PR update the sources with the JSDoc `@deprecated` annotation. Markdown has also been updated to reflect this change.
Additionally, contributing and development-related readme has been moved to `CONTRIBUTING.md`.

deprecating `@defichain/jellyfish` package

---

package-lock.json
package.json
packages/jellyfish-api-core/src/category/blockchain.ts
packages/jellyfish-api-jsonrpc/src/index.ts
packages/jellyfish-json/__tests__/precision.test.ts

- update typescript to 4.2.4
- removed ts-standard to use eslint
- fixed lint issues due to the recent updates

update typescript to 4.2.4 and eslint setup

---

packages/testcontainers/src/containers/RegTestContainer/ContainerGroup.ts

/kind fix
multiple test cases prune container clashing each other
Base on multiple occurrences in our test case, hypothesis made: Dockerode prune API is singleton, one execution at one time regardless the option is specifying particular container.
Fixes #

Disable docker pruning

---

.eslintrc
.idea/codeStyles/Project.xml
.idea/dictionaries/fuxing.xml
docs/node/RPC Category/16-loan.md
packages/jellyfish-api-core/__tests__/category/loan/depositToVault.test.ts
packages/jellyfish-api-core/__tests__/category/loan/getVault.test.ts
packages/jellyfish-api-core/__tests__/category/loan/listVaults.test.ts
packages/jellyfish-api-core/__tests__/category/loan/paybackLoan.test.ts
packages/jellyfish-api-core/__tests__/category/loan/setCollateralToken.test.ts
packages/jellyfish-api-core/__tests__/category/loan/setLoanToken.test.ts
packages/jellyfish-api-core/__tests__/category/loan/updateLoanToken.test.ts
packages/jellyfish-api-core/src/category/loan.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_loan_deposit_to_vault.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_loan_payback_loan.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_loan_set_collateral_token.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_loan_set_loan_token.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_loan_take_loan.test.ts
packages/jellyfish-transaction-builder/__tests__/txn/txn_builder_loan_update_loan_token.test.ts
packages/testcontainers/src/containers/RegTestContainer/LoanContainer.ts

/kind refactor
- Bump LoanContainer to `2.0.0`
- Updated `.eslintrc` and `.idea/` for better DX
- Refactor `loan.getVault` and `loan.listVault` interfaces in jellyfish-api-core to match different Vault states:
- `Vault` for empty states
- `VaultActive` for active state
- `VaultLiquation` for liquating state
- Added new verbose flag for `loan.listVault`
- Some internal DeFiD `DfTx` naming convention has been updated, this has been updated to reflect the changes to fix failing tests that rely on them.
> https://github.com/DeFiCh/jellyfish/issues/802 
Deposit to Vault 50% DFI requirements has been moved from `depositToVault` to `takeLoan`, additional testing needs to be done on TakeLoan.
```ts
// TODO: Logic moved to take loan (need to test it on take loan side instead)
it.skip('should be …
```

Bump LoanContainer to 2.0.0

---

.eslintrc
packages/jellyfish-api-core/__tests__/category/loan/withdrawFromVault.test.ts

/kind chore
Turn off eslint check `no-lone-blocks` in `__tests__/*` as it's cleaner to write tests in lone block to scope context.

turn off no-lone-blocks eslint check in testing

---

.idea/dictionaries/fuxing.xml
docs/node/RPC Category/01-blockchain.md
packages/jellyfish-api-core/__tests__/category/blockchain/waitForBlockHeight.test.ts
packages/jellyfish-api-core/__tests__/category/blockchain/waitForNewBlock.test.ts
packages/jellyfish-api-core/src/category/blockchain.ts

/kind feature
Add waitForNewBlock and waitForBlockHeight RPC, these 2 method is Node internal implementation to wait for the block. It does not fail when a new block doesn't come in. 
These 2 RPC interface is typed and added for downstream testing convenience. They are not very useful within the jellyfish context as the container wait function has auto-generate feature.

Add waitForNewBlock and waitForBlockHeight RPC

---

.github/workflows/release-publish.yml
package-lock.json
packages/jellyfish-address/package.json
packages/jellyfish-api-core/package.json
packages/jellyfish-api-jsonrpc/package.json
packages/jellyfish-block/package.json
packages/jellyfish-buffer/package.json
packages/jellyfish-crypto/package.json
packages/jellyfish-json/package.json
packages/jellyfish-network/package.json
packages/jellyfish-testing/package.json
packages/jellyfish-transaction-builder/package.json
packages/jellyfish-transaction-signature/package.json
packages/jellyfish-transaction/package.json
packages/jellyfish-wallet-classic/package.json
packages/jellyfish-wallet-encrypted/package.json
packages/jellyfish-wallet-mnemonic/package.json
packages/jellyfish-wallet/package.json
packages/testcontainers/package.json
packages/testing/package.json

/kind chore
This allows peer dependency to resolve automatically. 
This forces us to us use semantic versioning with `major.minor.patch`. Major as breaking, minor as any new non-breaking feature, patch to fix any non-breaking issue.

allow peer dependency to use ^ for jellyfish

---

.idea/dictionaries/fuxing.xml
package-lock.json
packages/jellyfish-wallet/package.json

`jellyfish-wallet` should include transaction-signature and transaction-builder dependencies by default.

add missing required dependencies for jellyfish-wallet

---

docs/node/RPC Category/16-loan.md
packages/jellyfish-api-core/__tests__/category/loan/listAuctons.test.ts
packages/jellyfish-api-core/src/category/loan.ts

/kind refactor
AuctionDetail object, the current return type of listAuction RPC is redundant. Should use the existing VaultLiquidation object
Fixes #

The return type of listAuctions RPC should be VaultLiquidation object

---

docs/node/CATEGORIES/16-loan.md
packages/jellyfish-api-core/__tests__/category/loan/getVault.test.ts
packages/jellyfish-api-core/__tests__/category/loan/listAuctons.test.ts
packages/jellyfish-api-core/__tests__/category/loan/listVaults.test.ts
packages/jellyfish-api-core/src/category/loan.ts

/kind fix
If an auction bid is made, display highestBid object that is returned from listVaults, getVault and listAuctions RPCs
Fixes #

Add highestBid object to listVaults, getVault and listAuctions RPCs

---

packages/testcontainers/src/containers/DeFiDContainer.ts

/kind chore
Since the latest docker updates testcontainers are getting timed out too frequently. This PR increases the timeout of testcontainers to 40s to make it more bearable for development and testing.

chore(packages/testcontainers): increase timeout of testcontainers to 40s so that it doesn't timeout

---

.github/PULL_REQUEST_TEMPLATE.md
.github/governance.yml
.github/labeler.yml
.github/labels.yml
.github/release-drafter.yml
.github/workflows/oss-governance-bot.yml
.github/workflows/oss-governance-labeler.yml
.github/workflows/release-publish.yml

As the project evolves, we need to evolve our project governance tooling to meet the needs of this mono-repo. As a continuation of #888 where we clearly outline each directory and its special interest. This PR automate the governance of issues, Pull Request, and release.
Moving from chat-ops, we now using semantic pull request titles with context. E.g:
- feat(apps/website...): title
- fix(packages/jellyfish-api-core): broken interface for abc
- chore(workflow): cleanup governance workflow
- docs(ocean): add oracles documentation
These will automatically be added to release with clearly defined context making it easier for the downstream consumer to understand the change and relevancy of each release to their usage.
We are cutting down on maintenance of labels to just a few high-level …

chore(workflow): project governance improvements

---

.idea/dictionaries/fuxing.xml
packages/jellyfish-api-core/src/category/masternode.ts

To fix a potential bug for `babel-loader`, refactor `masternode.createMasternode()` not to use ?? for self assignment of params.

refactor(packages/jellyfish-api-core): not to use ?? self assignment for createMasternode

---

.github/dependabot.yml

Reduce the number of labels created by @dependabot.

chore(workflow): add labels for dependabot.yml to reduce labels pollution

---

tsconfig.base.json

To fix downstream library consumers not able to compile.

chore(core): rollback tsconfig.base.json changes

---

.github/dependabot.yml
.github/labeler.yml
.github/workflows/release-publish.yml
.idea/codeStyles/Project.xml

Instead of double `deps(deps):` prefix to use `bump(context):` instead.

chore(workflow): updated governance automation to use bump prefix instead of deps

---

package-lock.json
packages/ocean-api-client/__tests__/ApiResponse.test.ts
packages/ocean-api-client/__tests__/OceanApiClient.test.ts
packages/ocean-api-client/__tests__/errors/ApiException.test.ts
packages/ocean-api-client/__tests__/errors/ClientException.test.ts
packages/ocean-api-client/__tests__/errors/TimeoutException.test.ts
packages/ocean-api-client/package.json
packages/ocean-api-client/src/ApiResponse.ts
packages/ocean-api-client/src/OceanApiClient.ts
packages/ocean-api-client/src/errors/ApiException.ts
packages/ocean-api-client/src/errors/ApiValidationException.ts
packages/ocean-api-client/src/errors/ClientException.ts
packages/ocean-api-client/src/errors/TimeoutException.ts
packages/ocean-api-client/src/index.ts
packages/ocean-api-client/tsconfig.build.json

DeFiChain Ocean API, next^2 generation API for building scalable Native DeFi Apps.
This is the foundational setup for Ocean API development integration into Jellyfish. Have been working on it for the past 3 weeks chipping off integration and migrating code slowly. This PR introduces 4 key concepts/packages with separation of concerns. Although the implementation example is small, they are fully featured working and tested.
As part of [#580](https://github.com/DeFiCh/jellyfish/issues/580) consolidation efforts. We had multiple projects that were extensions of the jellyfish project. The separated projects allowed us to move quickly initially but proves to be a bottleneck when it comes to development.
By including Ocean API development with jellyfish, it creates a better synergy of DeFiChain …

feat(ocean-api-client): add `ocean-api` client core

---

.idea/codeStyles/Project.xml
.idea/dictionaries/fuxing.xml
packages/testcontainers/__tests__/containers/RegTestContainer/Coinbase.test.ts
packages/testcontainers/src/containers/RegTestContainer/Masternode.ts

`@defichain/testcontainers` `waitForWalletCoinbaseMaturity` is kinda slow and it makes us wait 30-40 seconds between each test cycle. Pretty bad developer experience.
This PR introduces `mockTime=true` to simulate post genesis time at 5x speed to speed up the initial block minting process to get past coinbase limit quickly. It will restore to default system time after coinbase.
---
Alternatively, we can submit 100 pre-defined deterministic blocks. However, this design is less static and more dynamic allowing for greater testing evolution.

feat(testcontainers): add mockTime for waitForWalletCoinbaseMaturity to generate block faster

---

packages/jellyfish-testing/src/testing.ts
packages/testcontainers/__tests__/containers/ContainerRestart.test.ts
packages/testcontainers/src/containers/RegTestContainer/ContainerGroup.ts

/kind fix
Peers were lost after node restart.
Re-add node after restart.
Fixes #915
Easy (current):
```ts
node1.restart()
tGroup.link()
```
Manual
```ts
node1.restart()
node1.add(node2)
node1.add(node3)
```

fix(packages/testcontainers): add node after restart

---

docs/node/CATEGORIES/14-spv.md
packages/jellyfish-api-core/__tests__/category/spv/listAnchors.test.ts
packages/jellyfish-api-core/src/category/spv.ts
packages/testcontainers/src/containers/DeFiDContainer.ts

update listAnchor rpc to include start BTC height and limit
Fixes # https://github.com/DeFiCh/jellyfish/issues/911
relies on https://github.com/DeFiCh/ain/pull/921 to release before changing docker version

feat(jellyfish-api-core): listanchors supprot btcheight pagination

---

apps/ocean-api/__tests__/controllers/RawTxController.test.ts
apps/ocean-api/src/controllers/RawTxController.ts
apps/ocean-api/src/modules/ControllerModule.ts
packages/ocean-api-client/src/OceanApiClient.ts
packages/ocean-api-client/src/apis/RawTx.ts

Initial commit to add fee estimate to the `/rawtx` endpoint of OceanApi.
---
Different from the whale development testing style, everything in `apps/ocean-api` will be e2e tests only to keep things simple. Any spec if required should be tackled modularly and separated into their individual packages and tested in isolation.
This is 1 of 4 public Controller/Aspect that will be exposed for OceanApi.
- **RawTxController** 
- PlaygroundController
- RpcController
- GraphQLController

feat(ocean-api): add fee estimate to rawtx endpoint

---

apps/ocean-api/__tests__/modules/PlaygroundModule.test.ts
apps/ocean-api/src/modules/PlaygroundModule.ts
apps/ocean-api/src/modules/RootModule.ts

Integrated playground to automatically run when `PLAYGROUND_ENABLE` is provided on `regtest`.

feat(ocean-api): integrate playground with ocean-api

---

.eslintrc
examples/ocean-dbtc-burning-bot/.gitignore
examples/ocean-dbtc-burning-bot/README.md
examples/ocean-dbtc-burning-bot/build.js
examples/ocean-dbtc-burning-bot/package.json
examples/ocean-dbtc-burning-bot/src/main.ts
examples/ocean-dbtc-burning-bot/tsconfig.json

Ocean **dBTC** Burning Bot, part of DFIP 2201-A requirement; an automated wallet bot to burn **dBTC**.
> [DFIP 2201-A: Solving unbacked dBTC](https://github.com/DeFiCh/dfips/issues/101)
This is a very simple dBTC burning bot that is deployed on [df1qc8ptw6vc9588w6f53fvcjsjx0fntv3men407a9](https://defiscan.live/address/df1qc8ptw6vc9588w6f53fvcjsjx0fntv3men407a9) address.
**Implementation**
> BURN-DFI -> DFI Rewards -> BTC Swap -> BTC Burn
With a predefined [`main()`](./src/main.ts) as the entry function, this bot take all DFI accumulated from BURN-DFI pool rewards (3.5% from BTC-DFI). Swapping them from DFI to BTC and then finally sending it to the burn address `8defichainBurnAddressXXXXXXXdRQkSm`.
**Deployment**
Deployed on AWS lambda, this bot is compiled with …

docs(examples/ocean-dbtc-burning-bot): DFIP 2201-A, an automated wallet bot to burn dBTC

---

apps/ocean-api/package.json

Set `apps/ocean-api/package.json` `private: true`.

chore(apps/ocean-api): should be private as it should not be published into npm

---

.idea/dictionaries/fuxing.xml
examples/ocean-dex-bot/.gitignore
examples/ocean-dex-bot/README.md
examples/ocean-dex-bot/package.json
examples/ocean-dex-bot/src/main.ts
examples/ocean-dex-bot/tsconfig.json

Ocean DEX trading bot is a very simple bot that takes all `dUSDT` and converts them into `dDOGE`.
**Technical Design**
This Program assumes you always have enough `UTXO`. Only Account balances are used for trading. This bot just trades all `dUSDT` it has into `dDOGE`, no conditional logic is performed. You need to implement them yourself.
**Deployment**
Deployable on AWS lambda, this bot is compiled with [vercel/ncc](https://github.com/vercel/ncc) which produces a single file that supports TypeScript and binary addons (tiny-secp256k1). You are not required to deploy this on AWS lambda, it can simply be deployed as a NodeJS program.
```shell
npm i
npm run build
```

docs(examples/ocean-dex-bot): DEX trading bot powered with Ocean API using whale-api-client and whale-api-wallet

---

docs/node/CATEGORIES/03-net.md
packages/jellyfish-api-core/__tests__/category/loan/takeLoan.test.ts
packages/jellyfish-api-core/__tests__/category/net/getPeerInfo.test.ts
packages/jellyfish-api-core/src/category/net.ts
packages/testcontainers/src/containers/DockerContainer.ts

/kind feature
Added getPeerInfo rpc as part of ongoing #48

feat(jellyfish-api-core): add network getPeerInfo RPC

---

packages/jellyfish-network/src/TransactionSkipped.ts

Add missing method docs for `isSkippedTxId(txId, network)` in `@defichain/jellyfish-network`.

docs(jellyfish-network): add missing method description for isSkippedTxId

---

packages/jellyfish-address/__tests__/script/P2PKH.test.ts

Add burn address to be part of the address test suite.

chore(jellyfish-address): add test for burn address

---

packages/jellyfish-api-jsonrpc/src/index.ts

Add 422 status code to be parsed under ApiClientError.

chore(jellyfish-api-jsonrpc): properly parse 422 error for JsonRpcClient

---

packages/jellyfish-api-core/__tests__/category/blockchain/getBlockHash.test.ts

Ad test to handle the scenario of should getBlockHash but not found.

chore(jellyfish-api-core): add test for getblockHash not found

---

apps/ocean-api/package.json
apps/ocean-api/testing/OceanApiTesting.ts
apps/ocean-api/testing/OceanStubClient.ts
apps/ocean-api/testing/OceanStubServer.ts
jest.config.js

- fix jest.config.js not to resolve for @defichain/whale-api-client
- rename ocean-related in ocean-api/testing/* to Ocean... to differentiate project resources
Ref: https://github.com/DeFiCh/jellyfish/pull/1020

chore(ocean-api): Updated ocean-related testing framework

---

packages/testcontainers/src/containers/DeFiDContainer.ts

Bump `defi/defichain` to the latest release.

bump(testcontainers): DeFiDContainer defi/defichain to v2.6.1

---

.idea/dictionaries/fuxing.xml
packages/jellyfish-network/__tests__/BockSubsidy.test.ts
packages/jellyfish-network/src/BlockRewardDistribution.ts
packages/jellyfish-network/src/BlockSubsidy.ts

> Related to https://github.com/DeFiCh/whale/issues/310 and https://github.com/DeFiCh/whale/pull/661. This PR simplifies the development with a no-index, zero-lookup, instantaneous computation of supply, and block subsidy at a given height.
Inspired by https://github.com/DeFiCh/whale/pull/661, however, this PR introduces a deterministic DFI block subsidy and DFI supply calculation. All calculations within this utility class are in satoshi, test vectors are taken directly from c++ tests.
This class cache all 1252 reductions block subsidies and milestones allowing instantaneous computation. With very little memory footprint, 1252 x 2 BigNumber classes for both `getSupply` and `getBlockSubsidy`.
It introduces 2 public methods:
```ts
/**
* DFI supply calculation up to a given height are done …
```

feat(jellyfish-network): BlockSubsidy calculations

---

apps/legacy-api/__tests__/providers/WhaleApiClientProvider.test.ts
apps/legacy-api/src/controllers/MiscController.ts
apps/legacy-api/src/controllers/PoolPairController.ts
apps/legacy-api/src/controllers/TokenController.ts
apps/legacy-api/src/modules/ControllerModule.ts
apps/legacy-api/src/providers/WhaleApiClientProvider.ts

Creates a `WhaleApiClientProvider` that lazily initialises `WhaleApiClient`s and caches them by network (i.e. mainnet, regtest, testnet) so they can be reused - improving performance
Fixes #1052

chore(jellyfish-api-core): WhaleApiClient caching

---

docs/node/CATEGORIES/05-wallet.md
packages/jellyfish-api-core/__tests__/category/wallet/listWallets.test.ts
packages/jellyfish-api-core/src/category/wallet.ts

/kind feature
Add listWallets rpc as part of ongoing #48

feat(jellyfish-api-core): add wallet listWallets RPC

---

docs/node/CATEGORIES/08-account.md
packages/jellyfish-api-core/__tests__/category/account/getAccountHistory.test.ts
packages/jellyfish-api-core/src/category/account.ts
packages/testcontainers/src/containers/DeFiDContainer.ts

/kind feature
Currently, we have listaccounthistory on DeFiCh/ain. However, there isn't a way to filter to get one AccountHistory and we need an RPC to get single account history to resolve balance transfer.
Fixes https://github.com/DeFiCh/jellyfish/issues/1025

feat(jellyfish-api-core): add account getAccountHistory RPC

---

docs/node/CATEGORIES/03-net.md
packages/jellyfish-api-core/__tests__/category/net/setNetworkActive.test.ts
packages/jellyfish-api-core/src/category/net.ts

Disable/enable all p2p network activity
Added setNetworkActive rpc as part of ongoing #48

feat(jellyfish-api-core): add network setNetworkActive RPC

---

docs/node/CATEGORIES/11-masternode.md
packages/jellyfish-api-core/__tests__/category/masternode/isAppliedCustomTransaction.test.ts
packages/jellyfish-api-core/src/category/masternode.ts

Checks that custom transaction was affected on chain
Which issue(s) does this PR fixes?:
Added isAppliedCustomTransaction rpc as part of ongoing #48

feat(jellyfish-api-core): add masternode isAppliedCustomTransaction RPC

---

apps/legacy-api/__tests__/controllers/NetworkParamValidation.test.ts
apps/legacy-api/__tests__/providers/WhaleApiClientProvider.test.ts
apps/legacy-api/src/common/networks.ts
apps/legacy-api/src/controllers/MiscController.ts
apps/legacy-api/src/controllers/PoolPairController.ts
apps/legacy-api/src/controllers/TokenController.ts
apps/legacy-api/src/pipes/NetworkValidationPipe.ts
apps/legacy-api/src/providers/WhaleApiClientProvider.ts
apps/legacy-api/testing/LegacyApiTesting.ts
apps/legacy-api/testing/LegacyStubServer.ts

- Since WhaleApiClientProvider caches clients by network, currently it naively creates new clients based on the 'network' param. 
- Potential memory issues if the endpoints are spammed with invalid networks - the cache will get filled with clients that will never be cleared
- Solution: reject all invalid `network` values, as the WhaleApiClient doesn't validate the network value when instantiated. The only way it _detects_ an invalid network is when it tries to make the request and fails.
- Added a test to guard all registered routes in `legacy-api`
- Also refactored `'mainnet' | 'testnet' | 'regtest'` to use `NetworkName`

fix(apps/legacy-api): reject with 404 for queries with invalid network url param

---

.gitignore
.idea/.run/run-all-jest-tests-from-proj-root.run.xml

Add default run config for IDEA IDEs to run jest tests from project root (when you click the play button on the test suite)

chore(workflow): add default jest run config for IDEA IDEs

---

apps/legacy-api/__tests__/controllers/ActuatorController.test.ts
apps/legacy-api/__tests__/controllers/NetworkParamValidation.test.ts
apps/legacy-api/src/modules/ControllerModule.ts
apps/legacy-api/src/modules/RootModule.ts
apps/legacy-api/src/modules/WhaleApiModule.ts
package-lock.json

Adds `_actuator/probes/...` health check similar to Ocean API's
Fixes #1060
- Importing code directly from `apps/ocean-api` into `apps/legacy-api` causes some weirdness with Nest, hence duplicating the code is necessary at this stage --> refactoring work at #1078

chore(apps/legacy-api): legacy-api health check

---

apps/legacy-api/src/controllers/stats/LegacyStatsProvider.ts

BlockSubsidy objects eagerly perform calculations when constructed and cache results for faster look-ups later
Fixes #1116

refactor(apps/legacy-api): make blockSubsidy a class variable for perf

---

apps/legacy-api/__tests__/controllers/MiscController.test.ts
apps/legacy-api/src/controllers/MiscController.ts

Implementation of legacy-api to remap the legacy API:
- https://api.defichain.com/v1/validateaddress
- https://api.defichain.com/v1/getgov
Fixes part of #1024

feat(apps/legacy-api): Legacy API - validateaddress and getgov

---

Dockerfile

`Dockerfile` build was failing as `${APP}` is now redundant due to nestjs mono repo structural changes.
> #1073 will shift-left migrated invalid artifact in the future.

fix(docker): don't need to specify ${APP} twice in RUN ln due to nest-apps mono repo design update

---

apps/legacy-api/__tests__/controllers/StatsController.test.ts
apps/legacy-api/src/controllers/stats/LegacyStatsProvider.ts
apps/legacy-api/src/controllers/stats/StatsController.ts

/stats endpoint can return either a JSON object or just text, depending on the `?q=json.path` query param

chore(apps/legacy-api): set content-type header depending on stats type

---

docs/legacy/01-endpoints.md
website/docusaurus.config.js

- Move the DEX API docs from https://github.com/DeFiCh/ain/wiki/DEX-Api-Document into Jellyfish

chore(docs/legacy-api): move dex api docs into jellyfish

---

.github/scripts/release-report.js

- container link should not include `https://`
- format text to shift left as the indent doesn't trimmed automatically

fix(workflow): container link should not include `https://`

---

.github/workflows/release-apps.yml

Dependabot does not have access to publish containers so we skip PR container builds in those circumstances:
- https://github.com/DeFiCh/jellyfish/pull/1156#issuecomment-1058802501

feat(workflow): skip container builds for dependabot PRs

---

apps/legacy-api/__tests__/controllers/PoolPairController.test.ts
apps/legacy-api/src/controllers/PoolPairController.ts
apps/legacy-api/src/index.ts
apps/legacy-api/src/providers/WhaleApiClientProvider.ts

Implementation of https://api.defichain.com/v1/getsubgraphswaps in legacy-api
Which issue(s) does this PR fixes?:
Fixes part of https://github.com/DeFiCh/jellyfish/issues/1024
- query performance bottleneck is getaccounthistory

feat(apps/legacy-api): getsubgraphswaps

---

.github/scripts/release-report.js
.github/workflows/release-apps.yml

- All platforms must be present for release builds otherwise it will conflict due to platform OS label conflict.
- Also update release-report.js message add list indent
- Add `concurrency:` to cancel in progress workflow

fix(workflows/release-apps): all platforms must be present for release builds otherwise it will conflict

---

tsconfig.base.json

Due to the use of `cross-fetch` on `jellyfish-api-core`, we might need to add `lib: ["dom"]` so that is can build without error.
@kodemon this might be related to you.

chore(tsconfig): add `lib: ["dom"]` globally in tsconfig.base.json

---

apps/legacy-api/src/controllers/stats/LegacyStatsProvider.ts
apps/package.json
package-lock.json

In DeFiCh/whale [v0.27.0](https://github.com/DeFiCh/whale/releases/tag/v0.27.0) deprecate `getburninfo` RPC on ocean immediately.

chore(apps/legacy-api): LegacyStatsProvider.getBurnInfo to use `this.api.stats.getBurn` instead

---

.github/workflows/release-apps.yml
apps/legacy-api/src/controllers/stats/LegacyStatsProvider.ts

fix(legacy-api): burn info after RPC migration

---

apps/legacy-api/__tests__/controllers/PoolPairController.test.ts
apps/legacy-api/__tests__/controllers/TokenController.test.ts
apps/legacy-api/src/controllers/MiscController.ts
apps/legacy-api/src/controllers/PoolPairController.ts
apps/legacy-api/src/controllers/TokenController.ts
apps/legacy-api/src/controllers/stats/LegacyStatsProvider.ts
apps/package.json
package-lock.json

Since we are no longer targeting external package of `whale-api-client` we cannot use `/dist` targets. This PR removes the dependency on `/dist` and replaces it with `/src` as seen in other areas of apps in jellyfish. [Sample](https://github.com/DeFiCh/jellyfish/blob/main/apps/legacy-api/src/controllers/PoolPairController.ts#L16)
This PR depends on:
- https://github.com/DeFiCh/jellyfish/pull/1166
This is part of whale migration efforts:
- https://github.com/DeFiCh/jellyfish/pull/1168

feat(legacy-api): update `whale-api-client` imports

---

apps/package.json
package-lock.json

Remove `eslint` in `apps/package.json` as it's added globally in the mono repo, not used in apps.

chore(dependencies): remove eslint in `apps/package.json`

---

packages/jellyfish-wallet/__tests__/wallet.test.ts
packages/jellyfish-wallet/src/wallet.ts

Node and path derivation were previously embedded within `wallet.get()` routine. This makes it difficult for downstream implementation to use Wallet as an Abstraction to build custom patterns. This PR exposes those two functions as separate methods.
This PR also updates all wallet class parameters from `private readonly` to `protected readonly` for the same effect.

feat(packages/jellyfish-wallet): expose deriveNode and derivePath to allow better abstraction of Wallet

---

apps/playground-api/src/AppConfiguration.ts

Allow use of `BLOCKCHAIN_CPP_URL` in `apps/playground-api` with fallback to `PLAYGROUND_DEFID_URL`.

chore(apps/playground-api): allow use of BLOCKCHAIN_CPP_URL with fallback to PLAYGROUND_DEFID_URL

---

website/docusaurus.config.js

Release version v2.0.0-beta.17 deprecated `switchConfig` from the theme, causing build to fail.
https://github.com/facebook/docusaurus/releases/tag/v2.0.0-beta.17
Fixes #1223
Looks like they have plans for quite some breaking changes in their 2.0.0 release milestone.
https://github.com/facebook/docusaurus/milestone/15

chore(website): fix docusaurus failed build due to deprecation

---

.idea/dictionaries/fuxing.xml
docs/legacy/02-dex.mdx

Endpoint: https://api.defichain.com/v2/listswaps
> On the previous version of `/v1/listswaps`; `last_price` was mistakenly inverted. `/v2/listswaps` is the corrected
> version. `/v1/listswaps` is deprecated but still be supported.

docs(apps/legacy-api): 02-dex.mdx add corrected `/v2/listswaps` note

---

packages/jellyfish-wallet-mnemonic/__tests__/bip32.test.ts
packages/jellyfish-wallet-mnemonic/src/hd_node.ts

While BIP39 standard doesn't enforce validation of words to generate the HD seed, this implementation optionally allows you to validate the BIP39 word list before generating the MnemonicProviderData.
```ts
/**
* @param {boolean} [validate=false] optionally validate mnemonic words. While BIP39 standard doesn't enforce
* validation of words to generate the HD seed, this implementation optionally allow you to validate the BIP39 
* word list before generating the MnemonicProviderData.
*
* @throws {Error} if mnemonic sentence checksum invalid, if validate=true
*/
static wordsToData (words: string[], options: Bip32Options, validate: boolean = false): MnemonicProviderData {
if (validate && !validateMnemonicSentence(words)) {
throw new Error('mnemonic sentence checksum invalid')
}
// ...
}
```

feat(packages/jellyfish-wallet-mnemonic): validate 24 words optionally

---

packages/jellyfish-wallet/src/wallet_account.ts

`DeFiAddress.from()` in `packages/jellyfish-address` has been deprecated for some time now. This PR replace the use of it in `WalletAccount.addressToScript(address: string)` with the latest version.

refactor(packages/jellyfish-wallet): replace deprecated DeFiAddress.from() in WalletAccount

---

apps/legacy-api/src/index.ts
apps/legacy-api/testing/LegacyStubServer.ts

Change legacy-api to use RootServer to reduce code duplication

chore(apps/legacy-api): use rootserver for DRYness

---

.github/CODEOWNERS
apps/nest-cli.json
apps/package.json
apps/tsconfig.json

- exclude tests from tsbuild
- some references to `whale-api` still exist, but should be `whale` as it was changed: https://github.com/DeFiCh/jellyfish/pull/1248#pullrequestreview-918283735
Part of #977

chore(apps/whale): exclude tests from build and change 'whale-api' references to just 'whale'

---

apps/legacy-api/src/controllers/PoolPairController.ts

The routine `findPoolSwapDfTx` is running in a distributed environment where it requires the responding ocean node to have the same view of the blockchain to get `vouts[0]` for computing of Swap. However, in a distributed environment, you cannot guarantee all nodes have the exact same view at the same time. It's eventually consistent and therefore causing a race condition when resolving the swap history. This fix allow that routine to fail silently.

fix(apps/legacy-api): race condition fix in findPoolSwapDfTx when `vouts[0]` cannot be found

---

packages/rich-list-core/__tests__/RichListCore.test.ts
packages/rich-list-core/src/RichListCore.ts
packages/rich-list-core/test/RichListCoreTest.ts
packages/rich-list-core/test/StubbedWhaleClient.ts

This is a patch for `rich-list-core` which removes the use of `droppedFromRichList` single index db in the invalidation process.
This is due to the change in design decisions, from only storing the top 1000 richest, to keeping balance for every address instead.
This is a patch for #1084.

feat(rich-list-core): remove use of droppedFrom db for invalidation

---

apps/status-api/__test__/controllers/BlockchainController.test.ts
apps/status-api/src/controllers/BlockchainController.ts

Standardise path with oracles as per https://github.com/DeFiCh/jellyfish/pull/1315
Fixes #

refactor(status-api): Update Blockchain Status API path

---

apps/legacy-api/__tests__/controllers/PoolPairController.test.ts
apps/legacy-api/src/cache/SimpleCache.ts
apps/legacy-api/src/controllers/PoolPairController.ts
apps/legacy-api/src/modules/ControllerModule.ts
apps/legacy-api/src/modules/RootModule.ts
apps/legacy-api/testing/LegacyStubServer.ts

- Introduces block-level + transaction-level swap caching for getsubgraphswaps query path
- Recent blocks (within chain height - 2) are not cached as they could be invalidated. However, transaction-level swap cache enables us to call AccountHistory rpc at most once for any given txn, hence largely side-stepping the performance bottleneck.
- Unfortunately, it's not enough to just cache by txid of the pool swap. Although the bottleneck of accounthistory rpc is side-stepped with this, the times from traversing blocks and their transactions add up.
- Hence, I tried caching the swaps by block hash instead, although we probably shouldn't cache recent blocks since they could be invalidated / more swaps could be added to them. 
- This was great for performance! …

feat(apps/legacy-api): perf improvement with caching

---

docs/node/CATEGORIES/14-spv.md
packages/jellyfish-api-core/__tests__/category/spv/refundHtlcAll.test.ts
packages/jellyfish-api-core/src/category/spv.ts

Implements spv `spv_refundhtlcall` rpc call.
Fixes part of #202 
Need some confirmation with how the `ain` implementation of this rpc is. Right now `ain`'s implementation returns an array of strings, containing only one string, shown [here](https://github.com/DeFiCh/ain/blob/86f554f2454edc8c16684cac6f7332b437a991e0/src/spv/spv_wrapper.cpp#L1354-L1379).
The [rpc documentation from `ain`](https://github.com/DeFiCh/ain/blob/86f554f2454edc8c16684cac6f7332b437a991e0/src/spv/spv_rpc.cpp#L1126) however shows that it returns a string txid, which is not the case.
This current implementation for jellyfish deals with this by simply taking the first element of the returned array.
Edit: This rpc now returns a string array, faithful to its `ain` implementation.

feat(jellyfish-api-core): implement refundHtlcAll

---

packages/jellyfish-network/__tests__/BitcoinJsLib.test.ts
packages/jellyfish-network/src/BitcoinJsLib.ts
packages/jellyfish-network/src/index.ts

Add `getNetworkBitcoinJsLib` to support `bitcoinjs-lib` Network interface easily.
> https://github.com/bitcoinjs/bitcoinjs-lib

feat(packages/network): add getNetworkBitcoinJsLib to support bitcoinjs-lib

---

.github/CODEOWNERS
.github/workflows/oss-governance-bot.yml
.github/workflows/oss-governance-labeler.yml
.github/workflows/oss-governance-labels.yml
.github/workflows/release-drafter.yml

/kind chore
- Rename workflows related to "OSS Governance" into a single Workflow, renamed the job within to "Labels", "Labeler" and "Bot".
- Add `permissions:` for workflows to harden workflow security.
- Remov the use of `DEFICHAIN_BOT_GITHUB_TOKEN` for security hardening.
- Add `concurrency:` for workflows that requires it.
- Bump versions and migrate "OSS Governance Bot" to use the new org.

chore(workflows): cleanup workflow permissions and names

---

apps/status-api/README.md
apps/status-api/__tests__/controllers/OracleStatusController.test.ts
apps/status-api/src/controllers/OracleStatusController.ts

Previously, the logic for checking status of the oracle takes the first ticker returned from whale. However, some of the tickers are dormant, which means no data or outdated data will be returned, resulting in inaccurate status.
Fixes #

fix(status-api): Update to check status of first active tickers of the oracle

---

apps/legacy-api/__tests__/controllers/PoolPairController.test.ts

Updated v1 and v2 /listswaps regex to match tickers with a period

fix(legacy_api): Updated v1 and v2 /listswaps regex to match tickers with a period

---

package-lock.json
packages/whale-api-client/__tests__/WhaleApiClient.test.ts
packages/whale-api-client/package.json
packages/whale-api-client/src/Version.ts
packages/whale-api-client/src/WhaleApiClient.ts
packages/whale-api-client/src/WhaleApiResponse.ts
packages/whale-api-client/src/api/Address.ts
packages/whale-api-client/src/api/Blocks.ts
packages/whale-api-client/src/api/Loan.ts
packages/whale-api-client/src/api/MasterNodes.ts
packages/whale-api-client/src/api/Oracles.ts
packages/whale-api-client/src/api/PoolPairs.ts
packages/whale-api-client/src/api/Prices.ts
packages/whale-api-client/src/api/RawTx.ts
packages/whale-api-client/src/api/Rpc.ts
packages/whale-api-client/src/api/Tokens.ts
packages/whale-api-client/src/api/Transactions.ts
packages/whale-api-client/src/errors/WhaleApiException.ts
packages/whale-api-client/src/errors/WhaleApiValidationException.ts
packages/whale-api-client/src/errors/WhaleClientTimeoutException.ts
packages/whale-api-client/src/errors/index.ts
packages/whale-api-client/src/index.ts

Reverts some initial decisions during migration to adhere to the correct expectations of the original whale api client. This is mainly because of breaking expectations in tests compared to the original version.
Any further refactoring needs to be accompanied through a more complete onset of changes to every whale layer going forwards.
This is however a rather small revert simply adding back in what was removed during previous migration.
This is a precursor PR for whale api unit test migration:
- https://github.com/DeFiCh/jellyfish/pull/1250
Original migration PR:
- https://github.com/DeFiCh/jellyfish/pull/1166
This PR carries over changes made to whale-api-client in whale:
- https://github.com/DeFiCh/whale/commit/46698bfcf814219af673e709bc817bcc345cbf07#diff-0e10f6cd3807333a55b6653be4aca13 …

chore(whale-api-client): revert to original whale wrappers

---

apps/status-api/src/modules/WhaleApiModule.ts
packages/rich-list-core/test/StubbedWhaleClient.ts

- Fixes lint and build failing due to imported 'Method' that wasn't updated during the whale-api-client refactoring reversion
- Fixes WhaleApiClient not enforcing default values, causing status-api test failure due
Part of #977

fix(whale-migration): fix issues caused by reverting initial whale-api-client refactoring

---

packages/whale-api-client/src/api/Address.ts
packages/whale-api-client/src/api/PoolPairs.ts

Simple package sync with latest changes to whale repository to push forwards migration efforts and bringing it over the finish line.
This brings jellyfish up to date with changes in client and wallet packages to:
- https://github.com/JellyfishSDK/whale/commit/a93c495780bcbae1da38e8e642f0def493f3de96
Important note is that unit tests that depends on `src` in whale are not ported as part of the packages. Because of the migration being split into consolidated PRs the whale app has not been available to the packages during migration. Will also note that potentially we do not want to have packages being dependent on the project applications, so for application based testing we should keep them in the application scope.
I think we should be porting a refactored version of the unit tests into …

chore(whale): sync with whale packages

---

.github/workflows/ci.yml
apps/whale/__sanity__/WhaleSanityContainer.sanity.ts
packages/testcontainers/src/containers/AppContainer/WhaleSanityContainer.ts
packages/testcontainers/src/containers/AppContainer/index.ts

Ports over the sanity tests from https://github.com/JellyfishSDK/whale/blob/main/.github/workflows/ci/postman_collection.json as typescript + jest tests
Part of #977 
- One thing to note is that the CI pipeline now builds whale twice. We can investigate in a future PR the possibility of sharing the build (output of the `build` workflow) with the sanity test env.

chore(whale/sanity-testing): port over tests from whale ci newman

---

packages/whale-api-client/__tests__/api/account.history.test.ts
packages/whale-api-client/__tests__/api/address.test.ts
packages/whale-api-client/__tests__/api/address.vault.test.ts
packages/whale-api-client/__tests__/api/blocks.test.ts
packages/whale-api-client/__tests__/api/fee.test.ts
packages/whale-api-client/__tests__/api/loan.auction.history.test.ts
packages/whale-api-client/__tests__/api/loan.auction.test.ts
packages/whale-api-client/__tests__/api/loan.collateral.test.ts
packages/whale-api-client/__tests__/api/loan.scheme.test.ts
packages/whale-api-client/__tests__/api/loan.token.test.ts
packages/whale-api-client/__tests__/api/loan.vault.test.ts
packages/whale-api-client/__tests__/api/masternodes.test.ts
packages/whale-api-client/__tests__/api/oracles.test.ts
packages/whale-api-client/__tests__/api/poolpairs.swaps.test.ts
packages/whale-api-client/__tests__/api/poolpairs.test.ts
packages/whale-api-client/__tests__/api/prices.test.ts
packages/whale-api-client/__tests__/api/rawtx.test.ts
packages/whale-api-client/__tests__/api/rpc.test.ts
packages/whale-api-client/__tests__/api/stats.test.ts
packages/whale-api-client/__tests__/api/tokens.test.ts
packages/whale-api-client/__tests__/api/transaction.test.ts
packages/whale-api-client/__tests__/errors/api.error.test.ts
packages/whale-api-client/__tests__/errors/api.validation.exception.test.ts
packages/whale-api-client/__tests__/errors/client.timeout.exception.test.ts
packages/whale-api-client/__tests__/errors/index.test.ts
packages/whale-api-client/__tests__/stub.client.ts
packages/whale-api-client/__tests__/stub.service.ts
packages/whale-api-client/__tests__/whale.api.response.test.ts
packages/whale-api-client/__tests__/whale.rpc.client.test.ts
packages/whale-api-client/src/Version.ts

Moving the original unit tests from whale-api-client to jellyfish. This is done as a follow up to whale migration since the tests has a direct dependency on whale app code for the client stub. This is why we had to wait until the application layer was migrated before we could re-introduce these tests.
Test imports has been updated to support the new structure in jellyfish.
Depends on revert wrapper PR:
- https://github.com/DeFiCh/jellyfish/pull/1284
This is a follow up to whale migration PR:
- https://github.com/DeFiCh/jellyfish/pull/1248
- Has a direct dependency on `apps/whale`

chore(whale-api-client): migrate unit tests

---

apps/status-api/src/modules/ControllerModule.ts

Default network to mainnet when it is undefined for status-api
Application was not able to find ocean api causing the api calls to fail

fix(status-api): Default network to mainnet for status-api controller module

---

apps/legacy-api/__tests__/controllers/PoolPairController.test.ts

- Skip flaky tests that are getting in the way of PRs
- Due to legacy-api tests' reliance on ocean prod, any dip in ocean's performance (region-specific, likely due to increased traffic) would result in the tests failing. Hence skipping the tests for now to prevent repeated CI failures on every PR and marking a TODO for addressing the underlying issue.

chore(apps/legacy-api): skip flaky tests

---

packages/whale-api-client/__tests__/WhaleApiClient.test.ts
packages/whale-api-client/__tests__/stub.client.ts
packages/whale-api-client/src/Version.ts
packages/whale-api-client/src/WhaleApiClient.ts

Currently WhaleApiClient options version default to the current npm release version. I think to ensure forever backward compatibility for users, we should default to v0.
Duplicate of https://github.com/JellyfishSDK/whale/pull/980, changes raised here as part of migration
Fixes https://github.com/JellyfishSDK/whale/issues/979

chore(whale-api-client): Default whale api client to v0 and let url be optional

---

Dockerfile

On high trafficked whale instances the node heap limit of `2 gb` isn't enough.

chore(memory): increase node heap size to 4gb

---

.github/scripts/release-ecr-tags.js
.github/workflows/release-ecr.yml

Instead of executing docker command manually, attempt to build and push image via docker build-push-action to AWS ECR Public repo
Implement docker build and push image for other platforms
linux/amd64
linux/arm64
Fixes https://github.com/JellyfishSDK/jellyfish/issues/1432

chore(workflows): Refactor docker build to build-push-action

---

apps/legacy-api/__tests__/controllers/PoolPairController.test.ts
apps/legacy-api/src/controllers/PoolPairController.ts

- default totalLiquidity value to 0 (in case token is missing from ocean poolpair.totalLiquidity response)
- add '/v1' suffix to token name checking in legacy-api PoolPairController test
Part of #1532

fix(legacy-api): fix failing tests due to token split

---

apps/libs/caches/src/GlobalCache.ts
apps/whale-api/src/module.api/cache/defid.cache.ts
apps/whale-api/src/module.api/poolpair.controller.e2e.ts
apps/whale-api/src/module.api/poolpair.prices.service.ts

Fixes a regression by changing dexPrices calculator to rely on defid instead of tokenMapper
- Problem: token 49 (amzn/v1) and 89 (amzn) share the same `symbol` in `TokenMapper` due to #1532
- dexPrices logic depends on a map indexed by `symbol` - there was an assumption that `symbols` would be unique
- as there's a name collision (both have `symbol` = 'AMZN'), token 89 is overwritten by 49 in the dexPrices map, hence it never gets returned in the endpoint response
- Solution: change the dexPrices logic to rely solely on defid cache, remove any dependency on `TokenMapper`
- This is also more of a __future-proof__ fix in case similar token splits occur
Fixes a regression due to #1528

fix(whale-api): change to rely on defidcache instead of tokenMapper

---

apps/whale-api/src/module.api/_module.ts
apps/whale-api/src/module.api/stats.controller.ts

Tune `getLoanInfo` cache TTL due to the increased cost of running. Also expanded `CacheModule.options.max=10000` to increase the number of objects that can be cached on the CacheManager.

chore(whale-api/cache): tune cache parameters for `stats.controller.ts`

---

.github/scripts/release-report.js

We want to make it easier to find immutable historic version of previously built containers by going into the report history and seeing links to containers tagged with commit hashes.
This change will make previous commit hashes more apparent since the PR tag mutates onto the latest built container and cannot serve as a historic reference.
Fixes #1543

feat(docker): add commit hash version to docker container report

---

.github/workflows/dependencies.yml

Add consolidated dependencies bumping workflow for @nestjs and @docusaurus via GitHub workflows to reduce noise and simplify mono repo merging.

chore(workflows): add consolidated dependencies bumping workflow

---

apps/whale-api/src/app.configuration.ts
apps/whale-api/src/app.module.ts

- Fixes the `network` config being overwritten by Joi schema validation
- NestJS's ConfigModule expects the Joi schema to validate `process.env`, not the app config object
- ConfigModule will use `Joi.object({ network: Joi.string().default('regtest')})` to validate process.env
- It checks `network` and sees that it's missing from `process.env` (as the env variable is `WHALE_NETWORK`)
- So it sets the default value provided - `network: 'regtest'` - in ConfigService, overwriting the value provided by `load: [AppConfiguration]`

fix(whale-api): network value being overwritten by joi

---

.idea/dictionaries/fuxing.xml
apps/legacy-api/src/controllers/stats/LegacyStatsProvider.ts
apps/whale-api/src/module.api/stats.controller.ts
packages/whale-api-client/src/api/stats.ts

Partial fix for #1589 to remap `BurnInfo` from packages/jellyfish-api-core in `/stats/burn` to `BurnData` in packages/whale-api-client to prevent standards drift and causing breaking changes on whale due to upstream changes.
Partial fix for #1589, still need to wait for the `defid:2.9.x` change to be merged in to fix the real issue.

chore(whale-api): /stats/burn BurnInfo remapped to BurnData due to upstream standards drift

---

packages/jellyfish-transaction/__tests__/script/dftx/dftx_loans/WithdrawFromVault.test.ts
packages/jellyfish-transaction/__tests__/script/dftx/dftx_vault/WithdrawFromVault.test.ts

There are only 2 fixtures for withdrawFromVault DFTX. Adding 1 more fixture as the minimum requirement is at least 3 fixtures.
Also, withdrawFromVault uses J.  The letter S (0x53) should be changed to J (0x4a).
Fixes #1398

fix(packages/jellyfish-transaction): Add another fixture and fix wrong letter for withdrawFromVault DFTX
